### ISSUE TITLE
Problem using cppad as a cmake sub_directory()

### ISSUE THREAD

**Issue by whart222** [coin-or/CppAD#105]
I am trying to include CppAD in a large CMAKE package, but I'm having problems including CppAD using the sub_directory() declaration:

  add_subdirectory("src/CppAD")

The problem arises in the build for the examples.  For example, I am pulling-n CppAD from the src/CppAD directory inside my project.  Now in src/CppAD/example/multi_thread/openmp/CMakeLists.txt, the source_list variable is defined with the value ${CMAKE_SOURCE_DIR} .. but that points to the root of *my* software not the root of CppAD.

I think the fix is to use the CMAKE_CURRENT_SOURCE_DIR variable here and in other similar files.

**Comment by bradbell** [comment]
I think that `make` and `make install` will skip the examples and tests. Does this work for you ?

**Comment by whart222** [comment]
Yes, I think that’s even better.

Sent from my iPad

On Jun 1, 2021, at 9:38 PM, Brad Bell ***@***.***> wrote:

﻿

I think that make and make install will skip the examples and tests. Does this work for you ?

**Comment by bradbell** [comment]
As it turns out, because C++11 is not a requirement, we can completely remove the special routine for timing on Microsoft systems and this will remove the use of CMAKE_SOURCE_DIR. I am going to do that.

**Comment by whart222** [comment]
Nice.  😊

From: Brad Bell ***@***.***>
Sent: Wednesday, June 2, 2021 8:05 AM
To: coin-or/CppAD ***@***.***>
Cc: Hart, William E ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [coin-or/CppAD] Problem using cppad as a cmake sub_directory() (#105)


As it turns out, because C++11 is not a requirement, we can completely remove the special routine for timing on Microsoft systems and this will remove the use of CMAKE_SOURCE_DIR. I am going to do that.

**Comment by bradbell** [comment]
I think you should be able to use `add_subdirectory("src/CppAD")` with the current version; see 06-02 on
https://coin-or.github.io/CppAD/doc/whats_new_21.htm

Please test this.
If you are satisfied with the solution, please close this issue

**Comment by bradbell** [comment]
Closing issue without testing because @whart222 needs this feature (and so cannot test it).
