### ISSUE TITLE
CHECK_CXX_SOURCE_RUNS prevents cross-compilation

### ISSUE THREAD

**Issue by odow** [coin-or/CppAD#108]
We're building SHOT, which drags in CppAD: https://github.com/JuliaPackaging/Yggdrasil/pull/3290

The use of CHECK_CXX_SOURCE_RUNS in the CMAKE prevented us from cross-compiling. Isn't it sufficient to just use CHECK_CXX_SOURCE_COMPILES in most-cases?

**Comment by bradbell** [comment]
You may be correct that is is possible to just use CHECK_CXX_SOURCE_COMPILES.

The routine run_source_test
https://github.com/coin-or/CppAD/blob/master/cmake/run_source_test.cmake
acts as a wrapper for  CHECK_CXX_SOURCE_RUNS

Most all of the the use of  CHECK_CXX_SOURCE_RUNS is in
https://github.com/coin-or/CppAD/blob/master/include/cppad/CMakeLists.txt
The check of cppad_max_num_threads really uses execution, but it could be done in cmake code without an execution.

There is one other use I see in
https://github.com/coin-or/CppAD/blob/master/example/multi_thread/CMakeLists.txt

Would you please try converting for your example case and see how it works for you ?

**Comment by odow** [comment]
For now we're just shipping this patch:
https://github.com/JuliaPackaging/Yggdrasil/blob/88a544301c324a7ba4b7c8aef4c4a5d23d791181/C/Coin-OR/SHOT/bundled/patches/CppAD.patch#L2-L40
and everything seems to work okay.

You're right that the `cppad_max_num_threads` case should use execution, but that's okay for now because we don't modify it from the default https://github.com/coin-or/CppAD/blob/7c4e25cfce7aa1f5125345aeed05d464d300eb24/CMakeLists.txt#L180

**Comment by bradbell** [comment]
Do you have any suggestions for checking if a type is signed or not without  running the source. The current test runs the following program:
```
# include <limits>
int main(void)
{   bool is_unsigned = ! std::numeric_limits<${cmake_var}>::is_signed;
    return int( ! is_unsigned );
}
```
where `cmake_var` is a cmake variable contain the type being checked.

**Comment by bradbell** [comment]
I think that I have fixed this with the commit:
9edbb014eca397bca90dc0101ff9e57e7fbd7dcd
and the one before it.

Please check that it works for you and close this bug if you are satisfied.

**Comment by odow** [comment]
SHOT is still using https://github.com/coin-or/CppAD/commit/c93554b so I haven't tested, but this looks like it does the trick. Thanks!
