### ISSUE TITLE
Cross compilation issues

### ISSUE THREAD

**Issue by jcarpent** [coin-or/CppAD#111]
Dear @bradbell 
When trying to perform some cross-compilation with CppAD, I obtained this output from CMake:

```cmake
-- Performing Test cppad_has_gettimeofday
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   cppad_has_gettimeofday_EXITCODE (advanced)
   cppad_has_gettimeofday_EXITCODE__TRYRUN_OUTPUT (advanced)
  ```
  
  Do you know how to solve this issue?
  
  Thanks in advance,
  Justin

**Comment by bradbell** [comment]
I am not sure what is going on here. The error message is from TRY_RUN, but the test should only be checking for compilation (not running); 

see cppad_has_gettimeofday in
https://github.com/coin-or/CppAD/blob/master/include/cppad/CMakeLists.txt

see compile_source_test
https://github.com/coin-or/CppAD/blob/master/cmake/compile_source_test.cmake

The following text appears in the TRY_RUN documentation
https://cmake.org/cmake/help/latest/command/try_run.html
```
Behavior when Cross Compiling
New in version 3.3: Use CMAKE_CROSSCOMPILING_EMULATOR when running cross-compiled binaries.

When cross compiling, the executable compiled in the first step usually cannot be run on the build host. The try_run command checks the CMAKE_CROSSCOMPILING variable to detect whether CMake is in cross-compiling mode. If that is the case, it will still try to compile the executable, but it will not try to run the executable unless the CMAKE_CROSSCOMPILING_EMULATOR variable is set. Instead it will create cache variables which must be filled by the user or by presetting them in some CMake script file to the values the executable would have produced if it had been run on its actual target platform. These cache entries are:

**Comment by jcarpent** [comment]
Thanks @bradbell for the quick feedback.
Found a fix by setting CMAKE_CROSSCOMPILING_EMULATOR with cmake.
CppAD is now fully available for OSX arm64 architecture on conda. See https://github.com/conda-forge/cppad-feedstock
