### ISSUE TITLE
Windows Support in CppAD

### ISSUE THREAD

**Issue by proyan** [coin-or/CppAD#112]
Hello,
We've been using CppAD along with CppADCodegen for our packages (pinocchio, crocoddyl) for quite some time now, so first of all thank you for your good work. 

Our recent project involves creating the python bindings of CppAD ([pycppad](https://github.com/Simple-Robotics/pycppad)), and the bindings seem to be working on linux and macos systems.
However, while adding support for Windows, I had the following error:
```bash
  Checking Build System
  Building Custom Rule D:/a/pycppad/pycppad/python/CMakeLists.txt
  Building Custom Rule D:/a/pycppad/pycppad/CMakeLists.txt
  In file included from D:\a\pycppad\pycppad\src\cppad.cpp:6:
  In file included from D:\a\pycppad\pycppad\include\pycppad/codegen/cppadcg-scalar.hpp:8:
  In file included from C:\Miniconda\envs\pycppad\Library\include\cppad/cg/cppadcg.hpp:157:
  In file included from C:\Miniconda\envs\pycppad\Library\include\cppad/cppad.hpp:55:
  In file included from C:\Miniconda\envs\pycppad\Library\include\cppad/core/ad.hpp:25:
C:\Miniconda\envs\pycppad\Library\include\cppad/local/ad_tape.hpp(70,50): error : function template partial specialization is not allowed [D:\a\pycppad\pycppad\build\pycppad.vcxproj]
C:\Miniconda\envs\pycppad\Library\include\cppad/local/ad_tape.hpp(85,46): error : function template partial specialization is not allowed [D:\a\pycppad\pycppad\build\pycppad.vcxproj]
C:\Miniconda\envs\pycppad\Library\include\cppad/local/ad_tape.hpp(87,46): error : function template partial specialization is not allowed [D:\a\pycppad\pycppad\build\pycppad.vcxproj]
```
The full build is available [here](https://github.com/Simple-Robotics/pycppad/pull/12/checks?check_run_id=3410128003#step:6:125)

This error seems to be related to the [stackoverflow issue](https://stackoverflow.com/questions/63288453/visual-studio-2019-c-not-recognizing-template-friends/63729080) you raised one year ago, though is not the same. I wonder if you have any ideas about how to proceed.
Best,
Rohan

**Comment by proyan** [comment]
cc: @jcarpent, @nim65s

**Comment by bradbell** [comment]
I see you are using pycppad  ?
    https://github.com/b45ch1/pycppa
For reasons I will not go into, I switched over to using swig instead of boost to support the interface from python to CppAD; see
    https://github.com/bradbell/cppad_py
Are you aware of that interface ?

I assume the error message above was generated by the MS VisualStudio version of C++ ?
I am installing a version of Visual Studio Community 2019 and will see what happens when I try to test CppAD with it.

**Comment by bradbell** [comment]
Using Visual Studio 2019 and the current master for CppAD, I followed the instructions under Visual Studio on
file:///home/bradbell/repo/cppad.git/doc/cmake.htm#CMake%20Command.Visual%20Studio

The result of `make check` was that all the tests passed.

**Comment by jcarpent** [comment]
@bradbell Could you retry using clang-cl?

**Comment by jcarpent** [comment]
I've tried to provide a quick fix for this issue in #114.

**Comment by bradbell** [comment]
@proyan   I have merged https://github.com/coin-or/CppAD/pull/114 . Does this solve your problem ?

**Comment by proyan** [comment]
Hi @bradbell 
I've created a PR #117 that adds one remaining issue from the windows support of CppAD with CppADCodeGen.
The windows CI https://github.com/Simple-Robotics/pycppad/pull/18/checks?check_run_id=3449562010 is passing now.

**Comment by bradbell** [comment]
@proyan or @jcarpent 
I think this issue was has been fixed. If so, would you please close it.

**Comment by jcarpent** [comment]
@bradbell You're totally right.
Thanks for merging #145. 

Best,
Justin

**Comment by jcarpent** [comment]
@proyan Could you close this issue?
