### ISSUE TITLE
CMake project configuration

### ISSUE THREAD

**Issue by jcarpent** [coin-or/CppAD#113]
Dear @bradbell,

I've a minor question concerning the configuration of the project. Here:

https://github.com/coin-or/CppAD/blob/78de16aed04dee137d644b8f84041c7c3ca837b3/CMakeLists.txt#L201-L214

you manually defined the `CMAKE_BUILD_TYPE` according to the value of `${cppad_debug_which}` which in some sense suppressed the effect of any `CMAKE_BUILD_TYPE` provided when configuring the project.
What is the goal behind this design choice?
Would it be possible to rely on a more classical approach using `CMAKE_BUILD_TYPE`?

**Comment by bradbell** [comment]
This is something I did for CppADCodeGen. The requirement was to be able to mix debug and release versions of the library. The cppad_debug_which enables testing of this feature; see the heading cppad_debug_which on
https://coin-or.github.io/CppAD/doc/cmake.htm#cppad_debug_which

During testing, I randomly set debug_which to its possible values to ensure that this mixing of debug and release versions of the library works.

**Comment by jcarpent** [comment]
Thanks @bradbell for the quick feedback.
To be compliant with the common use of `CMAKE_BUILD_TYPE`, I would suggest not overwriting if is already defined.
Do you agree with that?

**Comment by bradbell** [comment]
I think you are suggesting that there should be no default fo cppad_debug_which and if it is not set, one should use CMAKE_BUILD_TYPE so that people get the expected behavior in that case ? This sounds reasonable to me.

**Comment by jcarpent** [comment]
My thought is that if `CMAKE_BUILD_TYPE` is defined by the user, which should stick to it. 
Otherwise, we can use the current behaviour.

**Comment by jcarpent** [comment]
Sorry for the late reply. This issues is correctly solved on my side.
Thanks a lot @bradbell.
