### ISSUE TITLE
Trailing comma in enum causes compiler error

### ISSUE THREAD

**Issue by tkralphs** [coin-or/CppAD#12]
The trailing comma in the enum [here](https://github.com/coin-or/CppAD/blob/master/cppad/local/atomic_base.hpp#L34) causes an error with gcc when called ```-pedantic-errors```.

**Comment by bradbell** [comment]
I see why this error was not caught by my testing. When you compile using g++ 5.1.1 with
   -Wall -ansi -pedantic-errors -Wshadow -g
you get the warning, but with
   -Wall -ansi -pedantic-errors -Wshadow -g -std=c++11 
you do not. I guess that the C++11 standard allows for trailing commas like this ?

I have tested and check in the change to github; see
https://github.com/coin-or/CppAD/commit/3bf661d259eb696cbed9201e090e5ad6fadad57f
 but there seems to be a problem with the coin svn server. I will send you and Matt a separate message about that.

**Comment by tkralphs** [comment]
Indeed, there is a pretty precise analysis [here](http://stackoverflow.com/questions/6372650/trailing-commas-and-c). Thanks for the fix.
