### ISSUE TITLE
Tried to set Option: xx. It is not a valid option. Please check the list of available options

### ISSUE THREAD

**Issue by hujunchao** [coin-or/CppAD#135]
Hi, When I use cppad， I meet this problem, can any kind person help me? Thank you!
EXIT: Optimal Solution Found.
Tried to set Option: print_level. It is not a valid option. Please check the list of available options.
tcmalloc: large alloc 1074249728 bytes == 0x4d468000 @
Tried to set Option: sb. It is not a valid option. Please check the list of available options.
Tried to set Option: max_iter. It is not a valid option. Please check the list of available options.
This is Ipopt version 3.14.4, running with linear solver MUMPS 5.4.1.

**Comment by bradbell** [comment]
Would you please provide a simple program that uses CppAD an generates this error message.

**Comment by bradbell** [comment]
@hujunchao 
Is this still a problem for you ?
