### ISSUE TITLE
AD<double> not working in Eigen with some complex function

### ISSUE THREAD

**Issue by nixwang** [coin-or/CppAD#156]
Hello, i'm here again for any help. 
AD<double> not working in Eigen with some complex function, like Eigen::EigenSolver.pseudoEigenvalueMatrix or pseudoEigenvectors, or Eigen::LDLT.solve.
Is there any suggestion, please.
Thanks a lot

**Comment by nixwang** [comment]
Sorry, the function is in a complex project, it need some time to extract a short example.
Thanks for your reply.

**Comment by bradbell** [comment]
Sometimes when I think there is a problem with a package, and I try to create a simple example demonstrating the problem, I realize that it was a mistake in my use of the package or a mistake in code that is not connected to the package.

**Comment by bradbell** [comment]
@nixwang Is this still an issue for you ?
