### ISSUE TITLE
Compilation problem with Visual C++ 2015

### ISSUE THREAD

**Issue by enricodetoma** [coin-or/CppAD#17]
`class ADTape` is now in `CppAD::local::` instead of `CppAD::`
This prevents compilation with Visual C++ 2015 with errors like this one:

`1>e:\DevTools\CppAD\cppad/core/pow.hpp(110): error C2248: 'CppAD::local::ADTape<Base>::id_': cannot access private member declared in class 'CppAD::local::ADTape<Base>'
`

To fix Visual C++ compilation, all these `friend` declarations:
`	friend AD<Base> pow <Base>
		(const AD<Base> &x, const AD<Base> &y);
`
should be changed to:
`	friend AD<Base> CppAD::pow <Base>
		(const AD<Base> &x, const AD<Base> &y);
`
because, for Visual C++, `pow` is actually `CppAD::local::pow`, and thus `CppAD::pow` is not a friend of a class in `CppAD::local::` namespace, unless the namespace is explicitly provided.

Would you like me to try to provide a pull request?

**Comment by enricodetoma** [comment]
I provided pull request #18 just in case...
But unfortunately I can't test it on any other compiler than Visual C++ 2015.
It should be a correct patch for any compiler, anyway.

**Comment by bradbell** [comment]
Thanks for pull request. I will test the change and get back to your.

It seems to me that things the CppAD namespace should be visible in the CppAD::local namespace, but perhaps there is something special about friend declarations in this regard ?

**Comment by enricodetoma** [comment]
I tried this simple test: http://ideone.com/TIORya and it also fails with gcc-5.1.
If you change:
`friend void test_fun(MyClass *c);`
to:
`friend void A::test_fun(MyClass *c);`
it works.

**Comment by bradbell** [comment]
I tested the change and it worked for me. I then accepted the pull request. Please close this issue, if the problem has been resolved for you.

**Comment by enricodetoma** [comment]
Thank you

**Comment by bradbell** [comment]
This change has been merged into cppad-20170000.1; see
https://github.com/coin-or/CppAD/commit/0201594a22c035232289215f8095c7ae308d194b
