### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by zrd1234** [coin-or/CppAD#172]
Hello, after installing CppAD on arm architecture, I wrote a test file to test it. When I compiled it, I encountered the following error.
<img width="558" alt="1680470580041" src="https://user-images.githubusercontent.com/96851901/229418489-03015bc5-f6b7-439d-8e24-2a1244322607.png">

**Comment by bradbell** [comment]
How did you solve your problem ? It seems from the message above that you were missing -lcppad_lib on the link line ?

**Comment by zrd1234** [comment]
> How did you solve your problem ? It seems from the message above that you were missing -lcppad_lib on the link line ?
Just connect the library to the terminal prompt.
