### ISSUE TITLE
Static library for non-windows builds

### ISSUE THREAD

**Issue by fontanf** [coin-or/CppAD#184]
Hi,

Currently, when compiling on a non-windows OS, only a dynamic library is generated. Could it be possible to generate a static library as well? or at least to have an option to do so?
I tried to manually change `SET(is_cppad_lib_dynamic 1)` to `SET(is_cppad_lib_dynamic 0)` and the compilation generated a static library as expected, but I haven't tested it.

**Comment by bradbell** [comment]
See that heading 09-08 on
https://cppad.readthedocs.io/en/latest/whats_new_23.html#whats-new-23-mm-dd-09-08

Please test that the new cmake option ``-D cppad_static_lib=true`` works for you.
If so, please close this issue.

Thanks.

**Comment by fontanf** [comment]
It works. Thank you for the fast update!
