### ISSUE TITLE
User's Guide URL on README.md 404s

### ISSUE THREAD

**Issue by raisin** [coin-or/CppAD#188]
The users guide link:

[https://cppad.readthedocs.io/en/latest/user_guide.html](
https://cppad.readthedocs.io/en/latest/user_guide.html)

under the Documentation subheading in the README.md file on the project's Github home page shows a 404 error when clicked.

**Comment by bradbell** [comment]
Thanks.
There were other broken links in the readme and it was out of date; see the commit.
https://github.com/coin-or/CppAD/commit/d1e2450827be9f301e780880db0eac355d0861ec

Please close this issue if you are satisfied with the changes.

**Comment by raisin** [comment]
Thanks for fixing the links.

There's one other minor issue. The install link on the README.md page links to the following url:

[https://cppad.readthedocs.io/latest/Install.html](
https://cppad.readthedocs.io/latest/Install.html)

The OMhelp link on that page links to the following page, which 404s:

[http://www.seanet.com/~bradbell/omhelp/](
http://www.seanet.com/~bradbell/omhelp/)

ps. The original issue was adequately resolved. I'm happy to open a separate ticket for this issue.

**Comment by bradbell** [comment]
See the heading 02-27 on
https://cppad.readthedocs.io/latest/2024.html#mm-dd-02-27

You can also look at
https://github.com/coin-or/CppAD/commit/1cf9370344bc16a5a071ce187c55c1c33641613c

**Comment by raisin** [comment]
Thanks for removing the omhelp links.

There's still a minor issue with xrst. The install link on the README.md page links to the following url:

[https://cppad.readthedocs.io/latest/Install.html](
https://cppad.readthedocs.io/latest/Install.html)

The xrst link on that page links to the following page, which 404s:

[https://cppad.readthedocs.io/latest/xrst.readthedocs.io](
https://cppad.readthedocs.io/latest/xrst.readthedocs.io)

ps. The original issue and the omhelp link issue were adequately resolved. I'm happy to open a separate ticket for this issue.

**Comment by bradbell** [comment]
I just checked the readme and it seems that all its links are working. Do you agree ? If so, would you please close this issue.

**Comment by raisin** [comment]
I don't agree. The xrst link 404s. Please see the following two screenshots:

![xrstLink](https://github.com/coin-or/CppAD/assets/2009181/f8f03970-b226-4615-b7ae-7353bdcea009)

When clicking the link shown in the screenshot above, here's the corresponding 404 error:

![404Error](https://github.com/coin-or/CppAD/assets/2009181/d0477074-9118-4473-9017-bea8c44eedb6)

However, this issue is different from the originally filed issue. If you'd like me to close the issue for that reason, I'm happy to do so.

**Comment by bradbell** [comment]
This is different from the readme file because it is in the documentation, which is generated by the xrst sphinx wrapper. Sphinx has the ability to check for broken external links and so I added that capability to xrst; see the heading 03-19 on
https://xrst.readthedocs.io/latest/2024.html#mm-dd-03-19

Using this option, I was able to find and fix all but two of the broken (and redirected) links in the CppAD documentaiton; see
https://github.com/coin-or/CppAD/commit/5cb9fd02106f522c68ece92bbc426fdde1fa95b2

**Comment by raisin** [comment]
Thanks for resolving this issue, and thanks for addressing my question. I'm going to close the issue since it's been fully resolve.
