### ISSUE TITLE
bin/get_colpack.sh Script Error

### ISSUE THREAD

**Issue by raisin** [coin-or/CppAD#189]
When I run the following, command:

`bin/get_colpack.sh`

I get the following error/output:

bin/get_colpack.sh: line 67: ./configure: No such file or directory

Note: I encountered this error on both Debian 12 and Ubuntu 22.04 LTS.

**Comment by raisin** [comment]
The entire input and output in the shell is provided.

`debianuser@debian:~/cppad.git$ bin/get_colpack.sh 
prefix=/home/debianuser/cppad.git/build/prefix
Executing get_colpack.sh
cd external
cd colpack.git
git checkout --quiet v1.0.10
./configure --prefix=/home/debianuser/cppad.git/build/prefix --libdir=/home/debianuser/cppad.git/build/prefix/lib64 --enable-static --enable-shared
bin/get_colpack.sh: line 67: ./configure: No such file or directory
`

**Comment by bradbell** [comment]
It appears that you do not have the autotools installed on your system and colpack requires that. There error messaging for this case should be better.

Looking just below line 118 in
https://github.com/coin-or/CppAD/blob/master/bin/get_colpack.sh
we see
```
echo_eval cd $package.git
echo_eval git checkout --quiet v$version
# -----------------------------------------------------------------------------
if which autoconf >& /dev/null
then
   echo_eval libtoolize
   echo_eval autoreconf --install --force
fi
```

Feel free to post a pull request that gives a better error message. Note that colpack is optional and can be left out (while including other optional packages); see package_prefix on
https://cppad.readthedocs.io/latest/cmake.html#package-prefix

**Comment by raisin** [comment]
Thanks - That was helpful. I'll create a pull request with a better error message. The README.md may be a bit misleading as indicated in the following annotation:

![AutotoolsRequired](https://github.com/coin-or/CppAD/assets/2009181/63ffee0b-17d6-47e6-9461-a8e72d6b518a)

**Comment by raisin** [comment]
I created the following merge request:

https://github.com/coin-or/CppAD/pull/190

**Comment by bradbell** [comment]
colpack uses the autotools to do it's install colpack.
CppAD uses cmake to build its tests and do its install.
CppAD can use colpack (if it is installed).

**Comment by raisin** [comment]
Thanks for the explanation. I see that you reviewed and merged my pull request. Thanks. I'm closing this issue.
