### ISSUE TITLE
Could NOT find GOOGLEHASH (missing: GOOGLEHASH_COMPILE)

### ISSUE THREAD

**Issue by raisin** [coin-or/CppAD#200]
On Ubuntu 22.04 LTS, when running:

`
bin/get_eigen.sh
`

I get the error message:

Could NOT find GOOGLEHASH (missing: GOOGLEHASH_COMPILE)

Furthermore, I get this error message when I checkout tag 3.3.7 of eigen. The corresponding commit is:

commit 21ae2afd4edaa1b69782c67a54182d34efe43f9c (HEAD, tag: 3.3.7)
Author: Gael Guennebaud <g.gael@free.fr>
Date:   Tue Dec 11 18:57:55 2018 +0100
bump to 3.3.7

However, the latest master branch of eigen is able to find GoogleHash. The program output is the following:

-- Found GoogleHash: /usr/include

Is it worth upgrading the eigen tag or version used by the bin/get_eigen.sh script?

Notes:
1.
I installed the Ubuntu 22.04LTS OS package:
libsparsehash-dev
2.
Out of curiosity, what Linux OS and version do you typically test with?
3.
With regards to Issue #183, I wasn't the one that opened it, but it seems the person opening it hasn't responded in quite some time.

**Comment by bradbell** [comment]
Thanks. Please try the following changes to your bin/get_eigen.sh and see if it works for you
```
diff --git a/bin/get_eigen.sh b/bin/get_eigen.sh
index ab3cfa1f9..902fbcec5 100755
--- a/bin/get_eigen.sh
+++ b/bin/get_eigen.sh
@@ -38,7 +38,8 @@
 # This will install the following version of Eigen
 # {xrst_spell_off}
 # {xrst_code sh}
-version='3.3.7'
+# This was the mater version on 2024-03-24
+version='a39ade4ccf99df845ec85c580fbbb324f71952fa'
 # {xrst_code}
 # {xrst_spell_on}
 #
```

**Comment by bradbell** [comment]
I changed get_eigen.sh to use the version above and change the cmake build to require c++14 or higher if eigen is included: see the heading 03-28 on
https://cppad.readthedocs.io/latest/2024.html#mm-dd-03-28

**Comment by raisin** [comment]
Thanks for fixing this. This works nicely now!
