### ISSUE TITLE
make check_cppad_ipopt Failure

### ISSUE THREAD

**Issue by raisin** [coin-or/CppAD#201]
Environment: Ubuntu 22.04 LTS

Steps To Reproduce:
1. bin/run_configure.sh
2. cd build
3. cmake .. -D include_ipopt=true
4. make check_cppadd_ipopt

Shell Output:
➜  build git:(master) ✗ make check_cppad_ipopt
[  0%] Building CXX object cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/cppad_ipopt_nlp.cpp.o
In file included from /home/bulky/explicit_solutions_through_backprop/cppad.git/include/cppad/utility.hpp:44,
                 from /home/bulky/explicit_solutions_through_backprop/cppad.git/include/cppad/cppad.hpp:18,
                 from /home/bulky/explicit_solutions_through_backprop/cppad.git/cppad_ipopt/src/cppad_ipopt_nlp.hpp:565,
                 from /home/bulky/explicit_solutions_through_backprop/cppad.git/cppad_ipopt/src/cppad_ipopt_nlp.cpp:7:
/home/bulky/explicit_solutions_through_backprop/cppad.git/include/cppad/utility/sparse2eigen.hpp:103:11: fatal error: Eigen/Sparse: No such file or directory
  103 | # include <Eigen/Sparse>
      |           ^~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/build.make:76: cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/cppad_ipopt_nlp.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:3629: cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3610: cppad_ipopt/CMakeFiles/check_cppad_ipopt.dir/rule] Error 2
make: *** [Makefile:1391: check_cppad_ipopt] Error 2

Diagnostic Information:
➜  cppad.git git:(master) ✗ find . -name "Sparse" 
./external/eigen.git/Eigen/Sparse
./external/eigen.git/build/build/prefix/include/eigen3/Eigen/Sparse

Questions:
1. What OS do you typically use for development and testing? Is it primarily Windows or a Unix system?

**Comment by bradbell** [comment]
Note that cppad_ipopt is deprecated 
https://cppad.readthedocs.io/latest/cppad_ipopt_nlp.html#deprecated-2012-11-28
You should use
https://cppad.readthedocs.io/latest/ipopt_solve.html#ipopt-solve-name

The script bin/get_eigen.sh should have create that directory ?
What happens when you execute ?
```
cd cppad.git
ls build/prefix/inclue | grep Eigen
```
Here is what I get:
```
temp>cat temp
cppad.git>cd temp
temp>cmake .. -D include_ipopt=true
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cmake_install_datadir = share
-- cmake_install_docdir = NOTFOUND
-- cmake_install_includedirs = include
-- cmake_install_libdirs = lib
-- cmake_defined_ok = TRUE
-- cppad_prefix = /usr/local
-- cppad_postfix = NOTFOUND
-- cppad_cxx_flags = 
-- cppad_profile_flag = NOTFOUND
-- cppad_testvector = cppad
-- cppad_max_num_threads = 48
-- cppad_tape_id_type = unsigned int
-- cppad_tape_addr_type = unsigned int
-- cppad_static_lib = FALSE
-- cppad_debug_and_release = TRUE
-- Performing Test minimal_cplusplus
-- Performing Test minimal_cplusplus - Success
-- minimal_cplusplus = 1
-- Performing Test use_cplusplus_2017_ok
-- Performing Test use_cplusplus_2017_ok - Success
-- use_cplusplus_2017_ok = 1
-- CMAKE_SYSTEM_NAME = Linux
-- cppad_debug_which = 
-- CMAKE_BUILD_TYPE = NOTFOUND
-- make check: avialable
-- include_adolc = FALSE
-- include_ipopt = true
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.9.5") 
-- Found ipopt pkg-config file
-- CMAKE_CXX_FLAGS_DEBUG = -g
-- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found Boost: /usr/lib64/cmake/Boost-1.81.0/BoostConfig.cmake (found version "1.81.0") found components: thread 
-- boost_prefix = /usr
-- Found /usr/include
-- Found /usr/lib
-- Checking for module 'ipopt'
--   Found ipopt, version 3.13.4
-- is_cppad_lib_dynamic = 1
-- cppad_c_compiler_cmd = cc
-- c_compiler_msvc_clang = 0
-- cppad_c_compiler_msvc_flags = 0
-- cppad_c_compiler_gnu_flags = 1
-- Performing Test compiler_has_conversion_warn
-- Performing Test compiler_has_conversion_warn - Success
-- compiler_has_conversion_warn = 1
-- cppad_boostvector = 0
-- cppad_cppadvector = 1
-- cppad_eigenvector = 0
-- cppad_stdvector = 0
-- Performing Test cppad_has_gettimeofday
-- Performing Test cppad_has_gettimeofday - Success
-- cppad_has_gettimeofday = 1
-- Performing Test cppad_tape_id_type_is_unsigned
-- Performing Test cppad_tape_id_type_is_unsigned - Success
-- cppad_tape_id_type_is_unsigned = 1
-- Performing Test cppad_tape_addr_type_is_unsigned
-- Performing Test cppad_tape_addr_type_is_unsigned - Success
-- cppad_tape_addr_type_is_unsigned = 1
-- Performing Test cppad_has_mkstemp
-- Performing Test cppad_has_mkstemp - Success
-- cppad_has_mkstemp = 1
-- Performing Test cppad_has_tmpnam_s
-- Performing Test cppad_has_tmpnam_s - Failed
-- cppad_has_tmpnam_s = 0
-- Performing Test cppad_is_same_unsigned_int_size_t
-- Performing Test cppad_is_same_unsigned_int_size_t - Failed
-- cppad_is_same_unsigned_int_size_t = 0
-- Performing Test cppad_is_same_tape_addr_type_size_t
-- Performing Test cppad_is_same_tape_addr_type_size_t - Failed
-- cppad_is_same_tape_addr_type_size_t = 0
-- Performing Test first_block_t_mod_double_zero
-- Performing Test first_block_t_mod_double_zero - Success
-- first_block_t_mod_double_zero = 1
-- Performing Test second_block_t_mod_double_zero
-- Performing Test second_block_t_mod_double_zero - Success
-- second_block_t_mod_double_zero = 1
-- soversion = 1949
-- Not Windows system so building shared cppad_lib
-- make check_val_graph: available
-- make check_example_abs_normal: available
-- make check_example_atomic_four_lin_ode: available
-- make check_example_atomic_four_mat_mul: available
-- make check_example_atomic_four_vector: available
-- make check_example_atomic_four: available
-- make check_example_atomic_three: available
-- make check_example_atomic_two: available
-- make check_example_chkpoint_two: available
-- make check_example_compare_change: available
-- make check_example_general: available
-- make check_example_get_started: available
-- make check_example_graph: available
-- make check_example_jit: available
-- make check_example_json: available
-- make check_example_multi_thread_openmp: available
-- pthread library path = /usr/lib64/libpthread.a
-- Looking for pthread_barrier_wait in pthread
-- Looking for pthread_barrier_wait in pthread - found
-- make check_example_multi_thread_pthread: available
-- Performing Test boost_multi_thread_ok
-- Performing Test boost_multi_thread_ok - Success
-- boost_multi_thread_ok = 1
-- make check_example_multi_thread_bthread: available
-- make check_example_multi_thread: available
-- make check_example_optimize: available
-- make check_example_print_for: available
-- make check_example_sparse: available
-- make check_example_utility: available
-- make check_example_valvector: available
-- make check_example_ipopt_solve: available
-- make check_example: available
-- make check_introduction: available
-- make check_test_more_deprecated_atomic_two: available
-- make check_test_more_deprecated_chkpoint_one: available
-- make check_test_more_deprecated: available
-- make check_test_more_compare_c_c: available
-- make check_test_more_compare_c_cpp: available
-- make check_test_more_compare_c: available
-- make check_test_more_debug_rel: available
-- make check_test_more_cppad_for_tmb: available
-- make check_test_more_general: available
-- make check_test_more: available
-- make check_speed_cppad: available
-- make check_speed_cppad_jit: available
-- make check_speed_double: available
-- make check_speed_example: available
-- make check_speed_program: available
-- make check_speed_xpackage: available
-- make check_speed: available
-- make check_cppad_ipopt_example: available
-- make check_cppad_ipopt_speed: available
-- make check_cppad_ipopt_test: available
-- make check_cppad_ipopt: available
-- Configuring done (3.8s)
-- Generating done (0.1s)
-- Build files have been written to: /home/bradbell/repo/cppad.git/temp
temp>make check_cppad_ipopt
[  0%] Building CXX object cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/cppad_ipopt_nlp.cpp.o
[  0%] Building CXX object cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/hes_fg_map.cpp.o
[  0%] Building CXX object cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/jac_g_map.cpp.o
[  0%] Building CXX object cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/sparse_map2vec.cpp.o
[  0%] Building CXX object cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/vec_fun_pattern.cpp.o
[  0%] Linking CXX static library libcppad_ipopt.a
[  0%] Built target cppad_ipopt
[  0%] Building CXX object cppad_lib/CMakeFiles/cppad_lib.dir/cpp_graph_op.cpp.o
[  0%] Building CXX object cppad_lib/CMakeFiles/cppad_lib.dir/cppad_colpack.cpp.o
[  0%] Building CXX object cppad_lib/CMakeFiles/cppad_lib.dir/csrc_writer.cpp.o
[  0%] Building CXX object cppad_lib/CMakeFiles/cppad_lib.dir/json_lexer.cpp.o
[  0%] Building CXX object cppad_lib/CMakeFiles/cppad_lib.dir/json_parser.cpp.o
[  0%] Building CXX object cppad_lib/CMakeFiles/cppad_lib.dir/json_writer.cpp.o
[ 20%] Building CXX object cppad_lib/CMakeFiles/cppad_lib.dir/link_dll_lib.cpp.o
[ 20%] Building CXX object cppad_lib/CMakeFiles/cppad_lib.dir/temp_file.cpp.o
[ 20%] Linking CXX shared library libcppad_lib.so
[ 20%] Built target cppad_lib
[ 20%] Building CXX object cppad_ipopt/test/CMakeFiles/cppad_ipopt_test.dir/test_more.cpp.o
[ 20%] Building CXX object cppad_ipopt/test/CMakeFiles/cppad_ipopt_test.dir/k_gt_one.cpp.o
[ 20%] Building CXX object cppad_ipopt/test/CMakeFiles/cppad_ipopt_test.dir/multiple_solution.cpp.o
[ 20%] Building CXX object cppad_ipopt/test/CMakeFiles/cppad_ipopt_test.dir/retape_k1_l1.cpp.o
[ 20%] Building CXX object cppad_ipopt/test/CMakeFiles/cppad_ipopt_test.dir/retape_k1_l2.cpp.o
[ 40%] Linking CXX executable cppad_ipopt_test
[ 40%] Built target cppad_ipopt_test
Begin test group cppad_ipopt/test
k_gt_one            OK
multiple_solution   OK
retape_k1_l1        OK
retape_k1_l2        OK
memory_leak         OK
All 5 tests passed.
End test group cppad_ipopt/test
[ 40%] Built target check_cppad_ipopt_test
[ 60%] Building CXX object cppad_ipopt/example/CMakeFiles/cppad_ipopt_example.dir/example.cpp.o
[ 60%] Building CXX object cppad_ipopt/example/CMakeFiles/cppad_ipopt_example.dir/get_started.cpp.o
[ 60%] Building CXX object cppad_ipopt/example/CMakeFiles/cppad_ipopt_example.dir/ode_check.cpp.o
[ 60%] Building CXX object cppad_ipopt/example/CMakeFiles/cppad_ipopt_example.dir/ode_fast_check.cpp.o
[ 60%] Building CXX object cppad_ipopt/example/CMakeFiles/cppad_ipopt_example.dir/ode_simple_check.cpp.o
[ 60%] Linking CXX executable cppad_ipopt_example
[ 60%] Built target cppad_ipopt_example
Begin test group cppad_ipopt/example
ipopt_get_started   OK
ode_simple_check    OK
ode_fast_check      OK
memory_leak         OK
All 4 tests passed.
End test group cppad_ipopt/example
[ 60%] Built target check_cppad_ipopt_example
[ 80%] Building CXX object cppad_ipopt/speed/CMakeFiles/cppad_ipopt_speed.dir/__/src/cppad_ipopt_nlp.cpp.o
[ 80%] Building CXX object cppad_ipopt/speed/CMakeFiles/cppad_ipopt_speed.dir/__/src/hes_fg_map.cpp.o
[ 80%] Building CXX object cppad_ipopt/speed/CMakeFiles/cppad_ipopt_speed.dir/__/src/jac_g_map.cpp.o
[ 80%] Building CXX object cppad_ipopt/speed/CMakeFiles/cppad_ipopt_speed.dir/__/src/sparse_map2vec.cpp.o
[ 80%] Building CXX object cppad_ipopt/speed/CMakeFiles/cppad_ipopt_speed.dir/__/src/vec_fun_pattern.cpp.o
[ 80%] Building CXX object cppad_ipopt/speed/CMakeFiles/cppad_ipopt_speed.dir/ode_speed.cpp.o
[ 80%] Building CXX object cppad_ipopt/speed/CMakeFiles/cppad_ipopt_speed.dir/speed.cpp.o
[100%] Linking CXX executable cppad_ipopt_speed
[100%] Built target cppad_ipopt_speed
ode    simple_retape_yes: seconds = 28.23: eval_r_count = 7403
ode     simple_retape_no: seconds = 24.10: eval_r_count = 1
ode      fast_retape_yes: seconds =  4.80: eval_r_count = 319841
ode       fast_retape_no: seconds =  6.20: eval_r_count = 283591
[100%] Built target check_cppad_ipopt_speed
[100%] Built target check_cppad_ipopt
temp>
```

**Comment by raisin** [comment]
➜  cppad.git git:(master) ls build/prefix/include | grep Eigen
➜  cppad.git git:(master) cd build/prefix/include 

The Eigen stuff doesn't seem to be in build/prefix/include despite the fact it was fetched and built. The following may also provide some insight:

➜  prefix git:(master) grep -r "Eigen/Sparse" .
./include/cppad/cg/dae_index_reduction/dummy_deriv.hpp:#include <Eigen/Sparse>

**Comment by bradbell** [comment]
Try the following:
```
https://github.com/coin-or/CppAD.git cppad.git
cd cppad.git
bin/get_eigen.sh
ls -l build/prefix/include
```
When I do this I get
```
cppad.git>ls -l build/prefix/include
total 4
lrwxrwxrwx. 1 bradbell bradbell  64 Apr 19 04:20 Eigen -> /home/bradbell/trash/cppad.git/build/prefix/include/eigen3/Eigen
drwxr-xr-x. 1 bradbell bradbell 100 Apr 19 04:20 eigen3
```

**Comment by raisin** [comment]
When I try your suggestion, there is no build directory. Even if I create a build directory after step 2, there is nothing inside after I run those 4 steps.

**Comment by bradbell** [comment]
I get the output below when running get_eigen.sh, what is the value of prefix that prints for you and do you have `get_eigen.sh: OK` at the end of its execution:
```
cppad.git>bin/get_eigen.sh
prefix=/home/bradbell/trash/cppad.git/build/prefix
Executing get_eigen.sh
mkdir external 
cd external
git clone https://gitlab.com/libeigen/$package.git eigen.git
Cloning into 'eigen.git'...
remote: Enumerating objects: 124622, done.
remote: Counting objects: 100% (776/776), done.
remote: Compressing objects: 100% (315/315), done.
remote: Total 124622 (delta 501), reused 724 (delta 460), pack-reused 123846
Receiving objects: 100% (124622/124622), 105.40 MiB | 7.41 MiB/s, done.
Resolving deltas: 100% (103118/103118), done.
cd eigen.git 
git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.
git checkout --quiet a39ade4
mkdir build
cd build
cmake -D CMAKE_INSTALL_PREFIX=/home/bradbell/trash/cppad.git/build/prefix ..
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
```
...
```
-- Installing: /home/bradbell/trash/cppad.git/build/prefix/include/eigen3/unsupported/Eigen/CXX11/src/util/CXX11Meta.h
-- Installing: /home/bradbell/trash/cppad.git/build/prefix/include/eigen3/unsupported/Eigen/CXX11/src/util/CXX11Workarounds.h
ln -s /home/bradbell/trash/cppad.git/build/prefix/include/eigen3/Eigen /home/bradbell/trash/cppad.git/build/prefix/include/Eigen
touch /home/bradbell/trash/cppad.git/external/eigen-a39ade4.configured
get_eigen.sh: OK
```

**Comment by raisin** [comment]
Thanks - I realized the problem. I'm using zsh and bin/get_eigen.sh doesn't specify the shell like the other bin/get_*.sh files.

Here's the output:
➜  cppad.git git:(master) bin/get_eigen.sh 
bin/get_eigen.sh: 84: [[: not found
prefix=build/prefix
Executing get_eigen.sh
mkdir external
cd external
git clone https://gitlab.com/libeigen/$package.git eigen.git

The problem occurs at line 84 of bin/get_eigen.sh since '[[' syntax isn't supported by sh and zsh. The fix is simple. I created a pull request. I'll leave this open until you accept (or reject) the pull request.

**Comment by raisin** [comment]
The missing Eigen/Sparse issue is resolved. Now, I'm getting an error that coin-or/IpIpoptApplication.hpp does not exist.

➜  build git:(master) make check_cppad_ipopt
[  0%] Building CXX object cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/cppad_ipopt_nlp.cpp.o
In file included from /home/bulky/trash/CppAD/include/cppad/ipopt/solve.hpp:397,
                 from /home/bulky/trash/CppAD/include/cppad/cppad.hpp:68,
                 from /home/bulky/trash/CppAD/cppad_ipopt/src/cppad_ipopt_nlp.hpp:565,
                 from /home/bulky/trash/CppAD/cppad_ipopt/src/cppad_ipopt_nlp.cpp:7:
/home/bulky/trash/CppAD/include/cppad/ipopt/solve_callback.hpp:9:11: fatal error: coin-or/IpIpoptApplication.hpp: No such file or directory
    9 | # include <coin-or/IpIpoptApplication.hpp>
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/build.make:76: cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/cppad_ipopt_nlp.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:3410: cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:3391: cppad_ipopt/CMakeFiles/check_cppad_ipopt.dir/rule] Error 2
make: *** [Makefile:1313: check_cppad_ipopt] Error 2
➜  build git:(master) cd ..
➜  CppAD git:(master) find . -name 'IpIpoptApplication.hpp'
./external/Ipopt/src/Interfaces/IpIpoptApplication.hpp
./build/prefix/include/coin-or/IpIpoptApplication.hpp

In addition, I have the following file:

➜  coin ls -alh /usr/include/coin/IpIpoptApplication.hpp 
-rw-r--r-- 1 root root 9.3K Oct 26  2021 /usr/include/coin/IpIpoptApplication.hpp

I'm not sure what environment variable needs to be tweeked in order to find this file.

**Comment by bradbell** [comment]
Thanks for helping track down these problems:

Try running the following command
```
find build -name 'IpIpoptApplication.hpp'
```
I get the following:
```
cppad.git>find build -name  'IpIpoptApplication.hpp'
build/prefix/include/coin-or/IpIpoptApplication.hpp
```

**Comment by raisin** [comment]
➜  CppAD git:(master) ✗ find build -name 'IpIpoptApplication.hpp'
build/prefix/include/coin-or/IpIpoptApplication.hpp

**In this case, the file is there. However, when I run make from the build directory, it expects the file to be located at:

CppAd.git/include/coin-or/IpIpoptApplication.hpp**

If I create the directory coin-or inside CppAd.git/include and then copy IpIpoptApplication.hpp into this newly created coin-or directory, the error message changes to the following:

➜  build git:(master) ✗ make
[100%] Built target cppad_lib
[100%] Building CXX object cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/cppad_ipopt_nlp.cpp.o
In file included from /usr/include/coin/IpJournalist.hpp:15,
                 from /home/bulky/trash/CppAD/include/coin-or/IpIpoptApplication.hpp:20,
                 from /home/bulky/trash/CppAD/include/cppad/ipopt/solve_callback.hpp:9,
                 from /home/bulky/trash/CppAD/include/cppad/ipopt/solve.hpp:397,
                 from /home/bulky/trash/CppAD/include/cppad/cppad.hpp:68,
                 from /home/bulky/trash/CppAD/cppad_ipopt/src/cppad_ipopt_nlp.hpp:565,
                 from /home/bulky/trash/CppAD/cppad_ipopt/src/cppad_ipopt_nlp.cpp:7:
/usr/include/coin/IpSmartPtr.hpp:18:4: error: #error "don't have header file for stddef"
   18 | #  error "don't have header file for stddef"
      |    ^~~~~
In file included from /home/bulky/trash/CppAD/include/cppad/ipopt/solve.hpp:397,
                 from /home/bulky/trash/CppAD/include/cppad/cppad.hpp:68,
                 from /home/bulky/trash/CppAD/cppad_ipopt/src/cppad_ipopt_nlp.hpp:565,
                 from /home/bulky/trash/CppAD/cppad_ipopt/src/cppad_ipopt_nlp.cpp:7:
/home/bulky/trash/CppAD/include/cppad/ipopt/solve_callback.hpp:10:11: fatal error: coin-or/IpTNLP.hpp: No such file or directory
   10 | # include <coin-or/IpTNLP.hpp>
      |           ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/build.make:76: cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/cppad_ipopt_nlp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3410: cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by bradbell** [comment]
See https://cppad.readthedocs.io/latest/ipopt.html
What do you get when you enter  ?
```
pkg-config ipopt --path --print-errors
```

**Comment by raisin** [comment]
➜  trash git clone https://github.com/coin-or/CppAD.git
Cloning into 'CppAD'...
remote: Enumerating objects: 123602, done.
remote: Counting objects: 100% (30554/30554), done.
remote: Compressing objects: 100% (5722/5722), done.
remote: Total 123602 (delta 24907), reused 30050 (delta 24555), pack-reused 93048
Receiving objects: 100% (123602/123602), 41.32 MiB | 4.64 MiB/s, done.
Resolving deltas: 100% (106499/106499), done.
➜  trash cd CppAD 
➜  CppAD git:(master) bin/get_optional.sh 
bin/get_colpack.sh 1>> get_optional.log 2>> get_optional.err
bin/get_colpack.sh: OK
bin/get_adolc.sh 1>> get_optional.log 2>> get_optional.err
bin/get_adolc.sh: OK
bin/get_eigen.sh 1>> get_optional.log 2>> get_optional.err
bin/get_eigen.sh: OK
bin/get_fadbad.sh 1>> get_optional.log 2>> get_optional.err
bin/get_fadbad.sh: OK
bin/get_ipopt.sh 1>> get_optional.log 2>> get_optional.err
bin/get_ipopt.sh: OK
bin/get_sacado.sh 1>> get_optional.log 2>> get_optional.err
bin/get_sacado.sh: OK
bin/get_cppadcg.sh 1>> get_optional.log 2>> get_optional.err
bin/get_cppadcg.sh: OK
get_optional: OK
➜  CppAD git:(master) cd build 
➜  build git:(master) cmake .. -D include_ipopt=true
-- cmake_install_datadir = share
-- cmake_install_docdir = NOTFOUND
-- cmake_install_includedirs = include
-- cmake_install_libdirs = lib
-- cmake_defined_ok = TRUE
-- cppad_prefix = /usr/local
-- cppad_postfix = NOTFOUND
-- cppad_cxx_flags = 
-- cppad_profile_flag = NOTFOUND
-- cppad_testvector = cppad
-- cppad_max_num_threads = 48
-- cppad_tape_id_type = unsigned int
-- cppad_tape_addr_type = unsigned int
-- cppad_static_lib = FALSE
-- cppad_debug_and_release = TRUE
-- minimal_cplusplus = 1
-- use_cplusplus_2014_ok = 1
-- use_cplusplus_2017_ok = 1
-- CMAKE_SYSTEM_NAME = Linux
-- cppad_debug_which = 
-- CMAKE_BUILD_TYPE = 
-- make check: avialable
-- include_adolc = FALSE
-- include_ipopt = true
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2")
-- Found ipopt pkg-config file
-- CMAKE_CXX_FLAGS_DEBUG = -g
-- CMAKE_CXX_FLAGS_RELEASE = -O3 -DNDEBUG
-- boost_prefix = /usr
-- Found /usr/include
-- Found /usr/lib
-- Checking for module 'ipopt'
--   Found ipopt, version 3.11.9
-- is_cppad_lib_dynamic = 1
-- cppad_c_compiler_cmd = cc
-- c_compiler_msvc_clang = 0
-- cppad_c_compiler_msvc_flags = 0
-- cppad_c_compiler_gnu_flags = 1
-- compiler_has_conversion_warn = 1
-- cppad_boostvector = 0
-- cppad_cppadvector = 1
-- cppad_eigenvector = 0
-- cppad_stdvector = 0
-- cppad_has_gettimeofday = 1
-- cppad_tape_id_type_is_unsigned = 1
-- cppad_tape_addr_type_is_unsigned = 1
-- cppad_has_mkstemp = 1
-- cppad_has_tmpnam_s = 0
-- cppad_is_same_unsigned_int_size_t = 0
-- cppad_is_same_tape_addr_type_size_t = 0
-- first_block_t_mod_double_zero = 1
-- second_block_t_mod_double_zero = 1
-- soversion = 1972
-- Not Windows system so building shared cppad_lib
-- make check_val_graph: available
-- make check_example_abs_normal: available
-- make check_example_atomic_four_lin_ode: available
-- make check_example_atomic_four_mat_mul: available
-- make check_example_atomic_four_vector: available
-- make check_example_atomic_four: available
-- make check_example_atomic_three: available
-- make check_example_atomic_two: available
-- make check_example_chkpoint_two: available
-- make check_example_compare_change: available
-- make check_example_general: available
-- make check_example_get_started: available
-- make check_example_graph: available
-- make check_example_jit: available
-- make check_example_json: available
-- make check_example_multi_thread_openmp: available
-- pthread library path = /usr/lib/x86_64-linux-gnu/libpthread.a
-- make check_example_multi_thread_pthread: available
-- boost_multi_thread_ok = 1
-- make check_example_multi_thread_bthread: available
-- make check_example_multi_thread: available
-- make check_example_optimize: available
-- make check_example_print_for: available
-- make check_example_sparse: available
-- make check_example_utility: available
-- make check_example_valvector: available
-- make check_example_ipopt_solve: available
-- make check_example: available
-- make check_introduction: available
-- make check_test_more_deprecated_atomic_two: available
-- make check_test_more_deprecated_chkpoint_one: available
-- make check_test_more_deprecated: available
-- make check_test_more_compare_c_c: available
-- make check_test_more_compare_c_cpp: available
-- make check_test_more_compare_c: available
-- make check_test_more_debug_rel: available
-- make check_test_more_cppad_for_tmb: available
-- make check_test_more_general: available
-- make check_test_more: available
-- make check_speed_cppad: available
-- make check_speed_cppad_jit: available
-- make check_speed_double: available
-- make check_speed_example: available
-- make check_speed_program: available
-- make check_speed_xpackage: available
-- make check_speed: available
-- make check_cppad_ipopt_example: available
-- make check_cppad_ipopt_speed: available
-- make check_cppad_ipopt_test: available
-- make check_cppad_ipopt: available
-- Configuring done (0.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/bulky/trash/CppAD/build
➜  build git:(master) make check_cppadd_ipopt 


make: *** No rule to make target 'check_cppadd_ipopt'.  Stop.
➜  build git:(master) make check cppadd_ipopt


[  0%] Building CXX object cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/cppad_ipopt_nlp.cpp.o
In file included from /home/bulky/trash/CppAD/include/cppad/ipopt/solve.hpp:397,
                 from /home/bulky/trash/CppAD/include/cppad/cppad.hpp:68,
                 from /home/bulky/trash/CppAD/cppad_ipopt/src/cppad_ipopt_nlp.hpp:565,
                 from /home/bulky/trash/CppAD/cppad_ipopt/src/cppad_ipopt_nlp.cpp:7:
/home/bulky/trash/CppAD/include/cppad/ipopt/solve_callback.hpp:9:11: fatal error: coin-or/IpIpoptApplication.hpp: No such file or directory
    9 | # include <coin-or/IpIpoptApplication.hpp>
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/build.make:76: cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/cppad_ipopt_nlp.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:3410: cppad_ipopt/src/CMakeFiles/cppad_ipopt.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1058: CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:169: check] Error 2
➜  build git:(master) pkg-config ipopt --path --print-errors
Unknown option --path
➜  build git:(master) pkg-config ipopt --print-errors 
➜  build git:(master) cd ..
➜  CppAD git:(master) pkg-config ipopt --print-errors
➜  CppAD git:(master) pkg-config ipopt path          
➜  CppAD git:(master) pkg-config ipopt path --print-errors
Package path was not found in the pkg-config search path.
Perhaps you should add the directory containing `path.pc'
to the PKG_CONFIG_PATH environment variable
No package 'path' found
➜  CppAD git:(master) cd build 
➜  build git:(master) pkg-config ipopt path --print-errors
Package path was not found in the pkg-config search path.
Perhaps you should add the directory containing `path.pc'
to the PKG_CONFIG_PATH environment variable
No package 'path' found
➜  build git:(master) echo $PKG_CONFIG_PATH

➜  build git:(master)

**Comment by bradbell** [comment]
Where is your ipopt.pc file located:
```
cppad.git>find build -name 'ipopt.pc'
build/prefix/lib/pkgconfig/ipopt.pc
```

**Comment by bradbell** [comment]
@raisin :
For the case above, one can use the following command to make sure that ipopt.pc is found by ``pkg-config`` :
```
export PKG_CONFIG_PATH="$(pwd)/build/prefix/lib/pkgconfig"
```
Note that ``$(pwd)`` is the current working directory.

**Comment by raisin** [comment]
Sorry for the slow reply. If I run the suggested command:

export PKG_CONFIG_PATH="$(pwd)/build/prefix/lib/pkgconfig"

from the project root directory before running:

cmake .. -D include_ipopt=true

the issue is resolved and 'cmake check' works properly. I missed the following in readthedocs:

https://cppad.readthedocs.io/latest/ipopt.html

On Ubuntu 22.04LTS, we should run:

pkg-config --variable=pcfiledir ipopt

instead of the following, which doesn't work:

pkg-config ipopt --path --print-errors

As indicated, this command should find the newly installed ipopt.pc file.

**Comment by raisin** [comment]
Thanks for the help resolving this issue. I wrote the message above in case anyone runs into the same issue and finds it helpful. Note: bradbell's suggested export command (in my previous post) was in my email thread but not in the comments posted above this message.
