### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by LiviuSandu** [coin-or/CppAD#23]
Good evening

I am a new user of the CppAD library. I tried to build it using Visual Studio 2015.

I performed all the preliminary steps, making the solution by the simplest command:

C:\cppad-20170805\build>cmake ..

When rebuilding the solution in Visual Studio 2015 I got the error message:

c1xx : fatal error C1083: Cannot open source file: 'NOTFOUND': No such file or directory

Surely, I missed something in the cmake command.

Please, can you help me fix this problem?

Thank you

Liviu Sandu

**Comment by bradbell** [comment]
I just tried downloading Visual Studio Community from
https://www.visualstudio.com/downloads

I could not find the file vcvarsall.bat which is used to set up command line processing with Visual Studio; see
https://stackoverflow.com/questions/43372235/vcvarsall-bat-for-visual-studio-2017

I did find the file vcvars.bat in the directory
c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd\ext
but it gave errors when I tried to execute it.

Were you able to get it to run ?

**Comment by LiviuSandu** [comment]
Hello Mr. Bell

First, I want to THANK YOU VERY MUCH for your help.
I am almost "desperate" to see the library working and build my programs
with. As well as I am eager to practise and learn more about AAD.
Yes, I could build everything smoothly. Only when trying to build the
solution I encountered the mentioned error (and a few others, but -I think-
this is the important one).
Let's discuss somehow and see how this problem can be solved. I can tell
you each step I performed to install the library.
I think it will be useful for further users too. What I did was to respect
TO THE LETTER the indications from Internet, that proved to be simple and
effective. Any beginner -as myself- will do the same when working with
Visual Studio. Hence, there are chances that this trouble will arise many
times and this is a pitty.

Best regards

Liviu Sandu

**Comment by bradbell** [comment]
Are you using the version of Visual Studio Community from 
https://www.visualstudio.com/downloads
If not, how can I get the version that you are using ?

What is the bat file you ran to set the visual studio variable ?; e.g.
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat

What were the command line arguments when you ran it ?; e.g.,
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

What is the output of your cmake command ?

**Comment by LiviuSandu** [comment]
Please, wait until this (late) evening when I shall be able to sit in front
of my laptop and answer all your questions. I am travelling now.

Best regards

Liviu

**Comment by LiviuSandu** [comment]
Hello

I finally arrived at some place where I can get an Internet connection.
That is why I answer so late. I apologize.


Below are the steps I performed to install and check the library (they are
on page https://www.coin-or.org/CppAD/Doc/download.htm at "Windows File
Extraction and Testing"  paragraph).


As the other environment variables were already set, I only had to set the
VCDIR variable:

C:\cppad-20170117\build>set VCDIR=C:\Program Files (x86)\Microsoft Visual
Studio 14.0\VC;%PATH%


I ran the vcvarsall.bat script:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>call vcvarsall.bat
x86

There was no output on the screen. I took a glance on the code and I think
this was the normal behaviour (although it shouldn't have been: I should
have been informed about a successful run). Because it needed some time to
get executed, I presumed all was right.


Then I ran the cmake script:

C:\cppad-20170805\build>cmake ..
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual
Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual
Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cmake_install_datadir = share
-- cmake_install_docdir = NOTFOUND
-- cmake_install_includedirs = include
-- cmake_install_libdirs = lib
-- cppad_prefix = /usr
-- cppad_postfix = NOTFOUND
-- cppad_cxx_flags = NOTFOUND
-- cppad_profile_flag = NOTFOUND
-- adolc_prefix = NOTFOUND
-- colpack_prefix = NOTFOUND
-- ipopt_prefix = NOTFOUND
-- sacado_prefix = NOTFOUND
-- eigen_prefix = NOTFOUND
-- fadbad_prefix = NOTFOUND
-- cppad_testvector = cppad
-- cppad_max_num_threads = 48
-- cppad_tape_id_type = unsigned int
-- cppad_tape_addr_type = unsigned int
-- cppad_debug_which = debug_all
-- cppad_deprecated = NO
-- CMAKE_CXX_FLAGS = /DWIN32 /D_WINDOWS /W3 /GR /EHsc
-- Could NOT find Boost
-- cppad_boostvector = 0
-- cppad_cppadvector = 1
-- cppad_eigenvector = 0
-- cppad_stdvector = 0
-- Performing Test cppad_has_signed_long_long_result
-- Performing Test cppad_has_signed_long_long_result - Success
-- cppad_has_signed_long_long = 1
-- Performing Test cppad_has_rvalue_result
-- Performing Test cppad_has_rvalue_result - Success
-- cppad_has_rvalue = 1
-- Performing Test cppad_has_nullptr_result
-- Performing Test cppad_has_nullptr_result - Success
-- cppad_has_nullptr = 1
-- Performing Test cppad_has_cstdint_8_to_64_result
-- Performing Test cppad_has_cstdint_8_to_64_result - Success
-- cppad_has_cstdint_8_to_64 = 1
-- Performing Test cppad_compiler_has_erf_result
-- Performing Test cppad_compiler_has_erf_result - Success
-- cppad_compiler_has_erf = 1
-- Performing Test cppad_compiler_has_asinh_result
-- Performing Test cppad_compiler_has_asinh_result - Success
-- cppad_compiler_has_asinh = 1
-- Performing Test cppad_compiler_has_acosh_result
-- Performing Test cppad_compiler_has_acosh_result - Success
-- cppad_compiler_has_acosh = 1
-- Performing Test cppad_compiler_has_atanh_result
-- Performing Test cppad_compiler_has_atanh_result - Success
-- cppad_compiler_has_atanh = 1
-- Performing Test cppad_compiler_has_expm1_result
-- Performing Test cppad_compiler_has_expm1_result - Success
-- cppad_compiler_has_expm1 = 1
-- Performing Test cppad_compiler_has_log1p_result
-- Performing Test cppad_compiler_has_log1p_result - Success
-- cppad_compiler_has_log1p = 1
-- Performing Test cppad_has_steady_clock_result
-- Performing Test cppad_has_steady_clock_result - Success
-- cppad_has_steady_clock = 1
-- cppad_cplusplus_201100_ok = 1
-- Performing Test cppad_has_gettimeofday_result
-- Performing Test cppad_has_gettimeofday_result - Failed
-- cppad_has_gettimeofday = 0
-- Performing Test cppad_size_t_not_unsigned_int_result
-- Performing Test cppad_size_t_not_unsigned_int_result - Failed
-- cppad_size_t_not_unsigned_int = 0
-- Performing Test cppad_tape_id_type_is_unsigned_result
-- Performing Test cppad_tape_id_type_is_unsigned_result - Success
-- cppad_tape_id_type_is_unsigned = 1
-- Performing Test cppad_tape_addr_type_is_unsigned_result
-- Performing Test cppad_tape_addr_type_is_unsigned_result - Success
-- cppad_tape_addr_type_is_unsigned = 1
-- Performing Test cppad_max_num_threads_is_integer_ge_4
-- Performing Test cppad_max_num_threads_is_integer_ge_4 - Success
-- Performing Test cppad_has_mkstemp_result
-- Performing Test cppad_has_mkstemp_result - Failed
-- cppad_has_mkstemp = 0
-- Performing Test cppad_has_tmpnam_s_result
-- Performing Test cppad_has_tmpnam_s_result - Success
-- cppad_has_tmpnam_s = 1
-- cppad_pkgconfig_cflags = -I/usr/include
-- cppad_pkgconfig_libs =
-- cppad_pkgconfig_requires =
-- make check_example_abs_normal: available
-- make check_example_atomic: available
-- make check_example_deprecated: available
-- make check_example_general: available
-- make check_example_get_started: available
-- make check_example_ipopt_solve: available
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: /openmp
-- make check_example_multi_thread_openmp: available
-- pthread library path = pthread_lib_path-NOTFOUND
-- make check_example_multi_thread: available
-- make check_example_optimize: available
-- make check_example_print_for: available
-- make check_example_sparse: available
-- make check_example_utility: available
-- make check_example: available
-- make check_introduction: available
-- make check_det_by_minor_c: available
-- make check_det_by_minor_cpp: available
-- make check_test_more_compare_c: available
-- make check_test_more_debug_rel: available
-- make check_test_more_general: available
-- make check_test_more: available
-- make check_speed_cppad: available
-- make check_speed_double: available
-- make check_speed_example: available
-- make check_speed: available
-- make check: avialable
-- Configuring done
CMake Warning (dev) at test_more/general/CMakeLists.txt:143
(ADD_DEPENDENCIES):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "cppad_lib" of target "test_more_general" does not
  exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: C:/cppad-20170805/build

Everything seemed right.


Then I opened the solution cppad (for Visual Studio 14) in directory
C:\cppad-20170805\build and tried to build it.

-------------------------------------------------------------------------------------------------------------------------------------------------------------------
Here, below, is the text of the script C:\Program Files (x86)\Microsoft
Visual Studio 14.0\VC\vcvarsall.bat I ran:



@echo off

REM VC command prompt depends on env. variable installed during VS. This
causes VC command prompt to break for C++ Build SKU.
REM So if VS is not installed and C++ Build SKU is installed, set
appropriate environment for C++ Build SKU by calling into it's batch file.
REM C++ Build SKU supports only desktop development environment.

if exist "%~dp0..\common7\IDE\devenv.exe" goto setup_VS
if not exist "%~dp0..\common7\IDE\wdexpress.exe" goto setup_buildsku

:setup_VS

if "%1" == "" goto x86
if "%2" == "" goto check_platform
setlocal
set _Argument2=%2
if not "%2"=="store" if not "%2"=="8.1" if not "%_Argument2:~0,3%"=="10."
goto usage
endlocal

:check_platform
if /i %1 == x86       goto x86
if /i %1 == amd64     goto amd64
if /i %1 == x64       goto amd64
if /i %1 == arm       goto arm
if /i %1 == x86_arm   goto x86_arm
if /i %1 == x86_amd64 goto x86_amd64
if /i %1 == amd64_x86 goto amd64_x86
if /i %1 == amd64_arm goto amd64_arm
goto usage

:x86
if not exist "%~dp0bin\vcvars32.bat" goto missing
call "%~dp0bin\vcvars32.bat" %2 %3
goto :SetVisualStudioVersion

:amd64
if not exist "%~dp0bin\amd64\vcvars64.bat" goto missing
call "%~dp0bin\amd64\vcvars64.bat" %2 %3
goto :SetVisualStudioVersion

:arm
if not exist "%~dp0bin\arm\vcvarsarm.bat" goto missing
call "%~dp0bin\arm\vcvarsarm.bat" %2 %3
goto :SetVisualStudioVersion

:x86_amd64
if not exist "%~dp0bin\x86_amd64\vcvarsx86_amd64.bat" goto missing
call "%~dp0bin\x86_amd64\vcvarsx86_amd64.bat" %2 %3
goto :SetVisualStudioVersion

:x86_arm
if not exist "%~dp0bin\x86_arm\vcvarsx86_arm.bat" goto missing
call "%~dp0bin\x86_arm\vcvarsx86_arm.bat" %2 %3
goto :SetVisualStudioVersion

:amd64_x86
if not exist "%~dp0bin\amd64_x86\vcvarsamd64_x86.bat" goto missing
call "%~dp0bin\amd64_x86\vcvarsamd64_x86.bat" %2 %3
goto :SetVisualStudioVersion

:amd64_arm
if not exist "%~dp0bin\amd64_arm\vcvarsamd64_arm.bat" goto missing
call "%~dp0bin\amd64_arm\vcvarsamd64_arm.bat" %2 %3
goto :SetVisualStudioVersion

:SetVisualStudioVersion
set VisualStudioVersion=14.0
goto :eof

:setup_buildsku
if not exist "%~dp0..\..\Microsoft Visual C++ Build Tools\vcbuildtools.bat"
goto usage
set CurrentDir=%CD%
call "%~dp0..\..\Microsoft Visual C++ Build Tools\vcbuildtools.bat" %1 %2
cd /d %CurrentDir%
goto :eof

:usage
echo Error in script usage. The correct usage is:
echo     %0 [option]
echo   or
echo     %0 [option] store
echo   or
echo     %0 [option] [version number]
echo   or
echo     %0 [option] store [version number]
echo where [option] is: x86 ^| amd64 ^| arm ^| x86_amd64 ^| x86_arm ^|
amd64_x86 ^| amd64_arm
echo where [version number] is either the full Windows 10 SDK version
number or "8.1" to use the windows 8.1 SDK
echo :
echo The store parameter sets environment variables to support
echo   store (rather than desktop) development.
echo :
echo For example:
echo     %0 x86_amd64
echo     %0 x86_arm store
echo     %0 x86_amd64 10.0.10240.0
echo     %0 x86_arm store 10.0.10240.0
echo     %0 x64 8.1
echo     %0 x64 store 8.1
echo :
echo Please make sure either Visual Studio or C++ Build SKU is installed.
goto :eof

:missing
echo The specified configuration type is missing.  The tools for the
echo configuration might not be installed.
goto :eof

**Comment by bradbell** [comment]
There is no VC directory in my
     c:\Program Files (x86)\Microsoft Visual Studio 14.0
directory, So I must have a different version of Visual Studio.
Is yours a free version ? If so, I can I download it ?

Looking at the heading generator in
https://www.coin-or.org/CppAD/Doc/cmake.htm#generator

Try running 
    cmake -G "NMake Makefiles" ..
and then
    make check

**Comment by LiviuSandu** [comment]
I tried cmake -G "NMake Makefiles" ..

It didn't work at all.

I received my Visual Studio 14 from a friend (as usual). It must be some
pirate copy. I don't try the Express version because I practise some MFC
sometimes or build dlls. As far as I know, these things can't be done by
Visual Studio Express. As I don't sell any software, there should be no
problem. I just want to learn.

I happened to find the installation file. The problem is, it is almost 6 GB
in size. How can I send it to you? (the file name is
tbe_ms_visual_studio_enterprise_x64_x86_with_update1.iso)

**Comment by bradbell** [comment]
If I am going to work on debugging, I want it to be for a system that is freely available on the Web; e.g.
https://www.visualstudio.com/downloads/

As I mentioned above, I had some problems with this. I thought perhaps you, or someone else, can figure out the how to run the  vcvars.bat file for that system. That part is a Microsoft complication and has nothing to do with CppAD.

**Comment by LiviuSandu** [comment]
OK. I shall download a Visual Studio Express version and try to install the
library there. That means I shall have to run the script. Maybe I can make
a comparison.

**Comment by LiviuSandu** [comment]
Hello

I downloaded the Visual Studio 2017 Community version (the free one).

I found the file vcvarsall.bat in directory C:\Program Files
(x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build and I
executed the call below, that succeeded (see lines below):

C:\Program Files (x86)\Microsoft Visual
Studio\2017\Community\VC\Auxiliary\Build>call vcvarsall.bat x86
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26430.16
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'


I ran cmake -G "NMake Makefiles" .. as required. It ran (see results below):

C:\cppad-20170808\build>cmake -G "NMake Makefiles" ..
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe --
works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual
Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe --
works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cmake_install_datadir = share
-- cmake_install_docdir = NOTFOUND
-- cmake_install_includedirs = include
-- cmake_install_libdirs = lib
-- cppad_prefix = /usr
-- cppad_postfix = NOTFOUND
-- cppad_cxx_flags = NOTFOUND
-- cppad_profile_flag = NOTFOUND
-- adolc_prefix = NOTFOUND
-- colpack_prefix = NOTFOUND
-- ipopt_prefix = NOTFOUND
-- sacado_prefix = NOTFOUND
-- eigen_prefix = NOTFOUND
-- fadbad_prefix = NOTFOUND
-- cppad_testvector = cppad
-- cppad_max_num_threads = 48
-- cppad_tape_id_type = unsigned int
-- cppad_tape_addr_type = unsigned int
-- cppad_debug_which = debug_all
-- cppad_deprecated = NO
-- CMAKE_CXX_FLAGS = /DWIN32 /D_WINDOWS /W3 /GR /EHsc
-- Could NOT find Boost
-- cppad_boostvector = 0
-- cppad_cppadvector = 1
-- cppad_eigenvector = 0
-- cppad_stdvector = 0
-- Performing Test cppad_has_signed_long_long_result
-- Performing Test cppad_has_signed_long_long_result - Success
-- cppad_has_signed_long_long = 1
-- Performing Test cppad_has_rvalue_result
-- Performing Test cppad_has_rvalue_result - Success
-- cppad_has_rvalue = 1
-- Performing Test cppad_has_nullptr_result
-- Performing Test cppad_has_nullptr_result - Success
-- cppad_has_nullptr = 1
-- Performing Test cppad_has_cstdint_8_to_64_result
-- Performing Test cppad_has_cstdint_8_to_64_result - Success
-- cppad_has_cstdint_8_to_64 = 1
-- Performing Test cppad_compiler_has_erf_result
-- Performing Test cppad_compiler_has_erf_result - Success
-- cppad_compiler_has_erf = 1
-- Performing Test cppad_compiler_has_asinh_result
-- Performing Test cppad_compiler_has_asinh_result - Success
-- cppad_compiler_has_asinh = 1
-- Performing Test cppad_compiler_has_acosh_result
-- Performing Test cppad_compiler_has_acosh_result - Success
-- cppad_compiler_has_acosh = 1
-- Performing Test cppad_compiler_has_atanh_result
-- Performing Test cppad_compiler_has_atanh_result - Success
-- cppad_compiler_has_atanh = 1
-- Performing Test cppad_compiler_has_expm1_result
-- Performing Test cppad_compiler_has_expm1_result - Success
-- cppad_compiler_has_expm1 = 1
-- Performing Test cppad_compiler_has_log1p_result
-- Performing Test cppad_compiler_has_log1p_result - Success
-- cppad_compiler_has_log1p = 1
-- Performing Test cppad_has_steady_clock_result
-- Performing Test cppad_has_steady_clock_result - Success
-- cppad_has_steady_clock = 1
-- cppad_cplusplus_201100_ok = 1
-- Performing Test cppad_has_gettimeofday_result
-- Performing Test cppad_has_gettimeofday_result - Failed
-- cppad_has_gettimeofday = 0
-- Performing Test cppad_size_t_not_unsigned_int_result
-- Performing Test cppad_size_t_not_unsigned_int_result - Failed
-- cppad_size_t_not_unsigned_int = 0
-- Performing Test cppad_tape_id_type_is_unsigned_result
-- Performing Test cppad_tape_id_type_is_unsigned_result - Success
-- cppad_tape_id_type_is_unsigned = 1
-- Performing Test cppad_tape_addr_type_is_unsigned_result
-- Performing Test cppad_tape_addr_type_is_unsigned_result - Success
-- cppad_tape_addr_type_is_unsigned = 1
-- Performing Test cppad_max_num_threads_is_integer_ge_4
-- Performing Test cppad_max_num_threads_is_integer_ge_4 - Success
-- Performing Test cppad_has_mkstemp_result
-- Performing Test cppad_has_mkstemp_result - Failed
-- cppad_has_mkstemp = 0
-- Performing Test cppad_has_tmpnam_s_result
-- Performing Test cppad_has_tmpnam_s_result - Success
-- cppad_has_tmpnam_s = 1
-- cppad_pkgconfig_cflags = -I/usr/include
-- cppad_pkgconfig_libs =
-- cppad_pkgconfig_requires =
-- make check_example_abs_normal: available
-- make check_example_atomic: available
-- make check_example_deprecated: available
-- make check_example_general: available
-- make check_example_get_started: available
-- make check_example_ipopt_solve: available
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: /openmp
-- make check_example_multi_thread_openmp: available
-- pthread library path = pthread_lib_path-NOTFOUND
-- make check_example_multi_thread: available
-- make check_example_optimize: available
-- make check_example_print_for: available
-- make check_example_sparse: available
-- make check_example_utility: available
-- make check_example: available
-- make check_introduction: available
-- make check_det_by_minor_c: available
-- make check_det_by_minor_cpp: available
-- make check_test_more_compare_c: available
-- make check_test_more_debug_rel: available
-- make check_test_more_general: available
-- make check_test_more: available
-- make check_speed_cppad: available
-- make check_speed_double: available
-- make check_speed_example: available
-- make check_speed: available
-- make check: avialable
-- Configuring done
CMake Warning (dev) at test_more/general/CMakeLists.txt:143
(ADD_DEPENDENCIES):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "cppad_lib" of target "test_more_general" does not
  exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: C:/cppad-20170808/build



I also ran nMake check, to build the examples. It failed(see below). I
looked for the strange NOTFOUND file name and I found it in file
build\CMakeCache.txt and C:\cppad-20170808\CMakeLists.txt. I haven't
realized yet how that name was used for a file to be opened, but this is
what I am trying to do.

Liviu

C:\cppad-20170808\build>nmake check

Microsoft (R) Program Maintenance Utility Version 14.10.25019.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Scanning dependencies of target speed_src
[  0%] Building CXX object
speed/src/CMakeFiles/speed_src.dir/link_det_lu.cpp.obj
NOTFOUND
c1xx: fatal error C1083: Cannot open source file: 'NOTFOUND': No such file
or directory
link_det_lu.cpp
Generating Code...
NMAKE : fatal error U1077:
'C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1410~1.250\bin\HostX86\x86\cl.exe'
: return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual
Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\nmake.exe"'
: return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual
Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\nmake.exe"'
: return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual
Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\nmake.exe"'
: return code '0x2'
Stop.

**Comment by bradbell** [comment]
I was able to reproduce this problem using cppad-20170805.gpl.tgz. To be specific, I got the error
C:\Users\bradl\cppad-20170805\build>nmake check
Microsoft (R) Program Maintenance Utility Version 14.10.25019.0
Copyright (C) Microsoft Corporation.  All rights reserved.
Scanning dependencies of target example_abs_normal
[  0%] Building CXX object example/abs_normal/CMakeFiles/example_abs_normal.dir/abs_eval.cpp.obj
NOTFOUND
c1xx: fatal error C1083: Cannot open source file: 'NOTFOUND': No such file or directory
... snip..

I am busy with some other things right now and  it may take some time for me to get to this bug. Perhaps if you posted a description on the mailing list, someone else would track it down in the meantime.

**Comment by bradbell** [comment]
Sorry for the long delay:

Please take a look at the heading msys2 and Visual Studio
http://coin-or.github.io/CppAD/doc/cmake.htm#CMake%20Command.msys2
http://coin-or.github.io/CppAD/doc/cmake.htm#CMake%20Command.Visual%20Studio


and see if the methods documented there work for you.

**Comment by bradbell** [comment]
Did the comments above solve your problem. If so, would you please close this issue.

**Comment by bradbell** [comment]
@LiviuSandu I am going to close this issue. If you are still having trouble with it, please re-open it.
