### ISSUE TITLE
make check fail

### ISSUE THREAD

**Issue by braunm** [coin-or/CppAD#24]
I am trying to install the latest version of CppAD from the GitHub master branch (15-Nov-2017).  At make check, I get the following error:

```
[ 78%] Built target check_example_general
Scanning dependencies of target example_get_started
[ 78%] Building CXX object example/get_started/CMakeFiles/example_get_started.dir/get_started.cpp.o
[ 80%] Linking CXX executable example_get_started
[ 80%] Built target example_get_started
Scanning dependencies of target check_example_get_started
f'(3) computed by CppAD = 142
[ 80%] Built target check_example_get_started
Scanning dependencies of target example_ipopt_solve
[ 80%] Building CXX object example/ipopt_solve/CMakeFiles/example_ipopt_solve.dir/get_started.cpp.o
In file included from /Users/braunm/cppad/example/ipopt_solve/get_started.cpp:52:
In file included from /Users/braunm/cppad/cppad/ipopt/solve.hpp:405:
/Users/braunm/cppad/cppad/ipopt/solve_callback.hpp:16:11: fatal error: 'coin/IpIpoptApplication.hpp' file not found
# include <coin/IpIpoptApplication.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [example/ipopt_solve/CMakeFiles/example_ipopt_solve.dir/get_started.cpp.o] Error 1
make[2]: *** [example/ipopt_solve/CMakeFiles/example_ipopt_solve.dir/all] Error 2
make[1]: *** [example/CMakeFiles/check_example.dir/rule] Error 2
make: *** [check_example] Error 2
mbraun: ~/cppad/build $ 
```

**Comment by bradbell** [comment]
What was the value of ipopt_prefix in the cmake command ?; see package_prefix on
https://www.coin-or.org/CppAD/Doc/cmake.xml#package_prefix

Where below the ipopt_prefix is the file coin/IpIpoptApplication.hpp located ?

Did the cmake command output mention ipopt and if so, what did it say with respect to ipopt ?

**Comment by braunm** [comment]
This is the cmake command I used:
~/cppad/build $ cmake -D cppad_prefix=/opt/cppad cppad_cxx_flags=-std=c++11 ..

in the output,  ipopt_prefix = NOTFOUND, but I was OK with that because I don't use ipopt at all.

Also, I get a cppad_cplusplus_201100_ok = 0 even with the above flag.  Not sure if that's important or relevant (but I do use C++11 in my own applications).

**Comment by bradbell** [comment]
I think the commit
https://github.com/coin-or/CppAD/commit/79a697abea4f0bc3d665f7cc0a20beb89868facd
fixed the problem. Please try the current version of the master to see if it works for you.

**Comment by braunm** [comment]
That appears to work.  Thanks.
