### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by joaoleal** [coin-or/CppAD#26]
Hello Brad,

Is there a chance of CppAD supporting metadata associated with each variable.
One could call something like 
```
AD<type> var = (...);
add_metadata(var, "key", "value");
```
This information could then be used to store information such as variable names and units.
An additional call to new functions (e.g., ``process_metadata_forward()`` and ``process_metadata_reverse()``) could be added in
cppad/local/forward0sweep.hpp
cppad/local/forward1sweep.hpp
cppad/local/forward2sweep.hpp
cppad/local/reverse_sweep.hpp

By default ``process_metadata_*()`` functions would be empty (no performance penalty would occur for types such as double/float).
These functions could be specialized for specific data types such as ``CppAD::cg::CG<>``.

This would allow me to recover the additional information that I need which cannot currently be saved in the tape.

Best regards,
João Leal

**Comment by bradbell** [comment]
As I understand, you would like the meta data stored in the tape ? 

I have thought of putting source code file and  line numbers in the tape, detecting infinities and nans, and then reporting the corresponding source code.

You have a different use for the extra information in the tape, and I should understand it.

Perhaps the right way to do it is to add yet another argument to the Independent function that signals more information about the recording; see
https://coin-or.github.io/CppAD/doc/independent.htm

**Comment by joaoleal** [comment]
At the moment I do need that feature anymore (I'm in different company now).
However, it could still be useful for cppad.
The idea was to associate each variable with additional information such as a variable name and units.
Perhaps there could be a function to associate additional information with a variable during the taping process.
It looks like a very similar feature to saving the line numbers.
Instead of integers for the line number, it would be strings (or pairs of strings) provided by the user.

**Comment by bradbell** [comment]
Does the base class object know the information when to operation is recorded. Perhaps it would be possible to extend the base class specifications to include a template function that has a default definition that is empty and that the compiler can know is empty.

**Comment by bradbell** [comment]
I am moving this issue to discussion https://github.com/coin-or/CppAD/discussions/84
