### ISSUE TITLE
configure.hpp missing error while using cppad, but this file does not exist

### ISSUE THREAD

**Issue by jumanamp** [coin-or/CppAD#27]

**Comment by bradbell** [comment]
This file is created by the cmake command; see
    https://coin-or.github.io/CppAD/doc/cmake.htm
and the file
    https://github.com/coin-or/CppAD/blob/master/cppad/configure.hpp.in

**Comment by bradbell** [comment]
Please close this bug if the comments above solved the problem for you.

**Comment by jumanamp** [comment]
Thanks, I didnt use cmake as I have to manually enter all parameters. I had directly done ../configure and make install in a build folder. With that approach the file was not created. Is there a reason?

**Comment by bradbell** [comment]
The configure script is deprecated and does not work as well as cmake; see
https://coin-or.github.io/CppAD/doc/autotools.htm

Is there a problem with running the cmake comand on your system ?  In its simplest form, I do
    mkdir build
    cd build
    cmake ..

You could also try running
    https://github.com/coin-or/CppAD/blob/master/bin/run_cmake.sh
and see if that works for you. Some times the simplest thing to do is to modify that script

**Comment by tkralphs** [comment]
This has also come up in building the COIN-OR Optimization Suite (see https://github.com/coin-or/coinbrew/issues/20#issuecomment-524055239). I see that there is an attempt at a fix in the latest master, but it is also broken. I open #49 for that, so I guess that issue now supersedes this one.

**Comment by bradbell** [comment]
I think this problem has been fixed and so am closing the issue. Please re-open the issue if it is still a problem.
