### ISSUE TITLE
Question on CheckSimpleVector

### ISSUE THREAD

**Issue by jcarpent** [coin-or/CppAD#30]
In the file `cppad/utility/check_simple_vector.hpp`, it appears that the size of a vector built with the default constructor should be zero.
```
    // size member function
    CPPAD_ASSERT_KNOWN(
      d.size() == 0,
      "default construtor result does not have size zero"
    ); 
```
My question is why this aspect is required (at least in debug mode)?
In this case, it appears impossible to use Eigen fixed-size vector for instance.

**Comment by bradbell** [comment]
CppAD assumes that all the operations specified in
https://coin-or.github.io/CppAD/doc/simplevector.htm
as supported by the vector types used as arguments.

Is it possible to set up a view of the fixed size vector as a dynamic size vector and then pass that into CppAD ?

**Comment by bradbell** [comment]
If you do not have more questions about this issue, would you please close it.

**Comment by jcarpent** [comment]
Sorry for my late answer. Yes, we can indeed use view to mimic dynamic size vectors, but I would have expected to not have to do it.

Anyway, thanks a lot for your quick feedback!
