### ISSUE TITLE
Citing CppAD

### ISSUE THREAD

**Issue by jcarpent** [coin-or/CppAD#33]
I would like to cite CppAD in a scientific paper.
@bradbell Do you have any preference for the citation? Any paper that describes the framework?

Thanks in advance!

**Comment by bradbell** [comment]
Bell, B.: CppAD: a package for C++ algorithmic differentiation (yyyymmdd).
http://www.coin-or.org/CppAD

Where yyyymmdd is the year, month, and day for version number that was used for the work. If use a stable version (where mmdd is 0000) then just yyyy is sufficient.

**Comment by jcarpent** [comment]
Perfect. Thanks for this quick reply and many thanks for providing open source access to your framework.
