### ISSUE TITLE
No unistd.h in Windows

### ISSUE THREAD

**Issue by tkralphs** [coin-or/CppAD#38]
The file `check_for_nan.hpp` includes `unistd.h`. With the Visual Studio 2015 compiler, it seems this should be `io.h` (or at least this is enough to make the OS build go through). I'm not sure how you prefer to fix this. I can submit a PR with `#ifdef _MSC_VER` or you may prefer to add checks for `unistd.h` and `io.h` to `configure.ac`. 

I'm building using the autotools and `cl` in MSys2, but this isn't specific to the autotools, as far as I can see. This should also break the build with CMake on Windows.

**Comment by bradbell** [comment]
Thanks for the report. I need to get a windows system up and running for testing and reproduce your problems. Give me a day or two.

**Comment by bradbell** [comment]
@tkralphs I think this problem has been solved and am closing the issue. Please re-open it if it is still a problem.
