### ISSUE TITLE
Undefined reference to `Ipopt::IpoptApplication::IpoptApplication(bool, bool)'

### ISSUE THREAD

**Issue by Jackhe96** [coin-or/CppAD#39]
I am completely new to cppad and I apologize if this is a stupid question. I have been trying to install cppad and ipopt for a day now and it's getting really frustrating as I don't know how to solve this problem. I am trying to use Cppad in my program but I run into the error:

In function `void CppAD::ipopt::solve<CppAD::vector<double>, (anonymous namespace)::FG_eval>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, CppAD::vector<double> const&,CppAD::vector<double> const&, CppAD::vector<double> const&, CppAD::vector<double> const&, CppAD::vector<double> const&, (anonymous namespace)::FG_eval&, CppAD::ipopt::solve_result<CppAD::vector<double> >&)':
ipopt_test.cpp:(.text+0xe0a): undefined reference to `Ipopt::IpoptApplication::IpoptApplication(bool, bool)'
collect2: error: ld returned 1 exit status

I can't find many resources online of people having the same problem. To check if it is my program I tried running the following [example]( https://www.coin-or.org/CppAD/Doc/ipopt_nlp_get_started.cpp.htm) but I get the same error. Wondering if you guys know about it

**Comment by bradbell** [comment]
Please close this issue if the answer above solved this problem.

**Comment by lxjlu** [comment]
I also have the same question. How do you solve it in the end? Thanks!

**Comment by Jackhe96** [comment]
@lxjlu It was my fault, I was using ROS and the cmakelists.txt file was not configured correctly

**Comment by lxjlu** [comment]
> @lxjlu It was my fault, I was using ROS and the cmakelists.txt file was not configured correctly

I also used it for the first time, and I understand whether it is a problem in the link section. I am directly g++ -o example example.cpp. Is there any problem, thank you.

**Comment by bradbell** [comment]
I assume you are using Ipopt and have installed it.

If on your cmake command line you choose cmake_verbose_makefile eqaul to YES
https://coin-or.github.io/CppAD/doc/cmake.htm#cmake_verbose_makefile

and you also specify ipopt_prefix
https://coin-or.github.io/CppAD/doc/cmake.htm#package_prefix

then during the make check
https://coin-or.github.io/CppAD/doc/cmake.htm#make%20check

you should see how CppAD links in ipopt.

**Comment by lxjlu** [comment]
> I assume you are using Ipopt and have installed it.
> 
> If on your cmake command line you choose cmake_verbose_makefile eqaul to YES
> https://coin-or.github.io/CppAD/doc/cmake.htm#cmake_verbose_makefile
> 
> and you also specify ipopt_prefix
> https://coin-or.github.io/CppAD/doc/cmake.htm#package_prefix
> 
> then during the make check
> https://coin-or.github.io/CppAD/doc/cmake.htm#make%20check
> 
> you should see how CppAD links in ipopt.

Thanks, I will check it carefully.

**Comment by bradbell** [comment]
It will be easier to see if you only check to ipopt_solve examples; i.e., use
make check_example_ipopt_solve

**Comment by tu-trinh** [comment]
@Jackhe96 Hi, I'm running into the exact same error. How did you fix your cmakelists.txt?

**Comment by bradbell** [comment]
By the exact same error do you mean ?
```
undefined reference to Ipopt::IpoptApplication::IpoptApplication(bool, bool)'
collect2: error: ld returned 1 exit status
```

**Comment by DanielrdMorais** [comment]
I have the same problem:
undefined reference to `Ipopt::IpoptApplication::IpoptApplication(bool, bool)'
collect2: error: ld returned 1 exit status
