### ISSUE TITLE
Problems linking boost multi-threading library

### ISSUE THREAD

**Issue by niclasbrok** [coin-or/CppAD#42]
When using eigen as cppad_testvector I get the error:

![image](https://user-images.githubusercontent.com/8836802/51323934-c3c70880-1a69-11e9-8231-b59bea1993a8.png)

I made the following cmake call:

`cmake -D CMAKE_VERBOSE_MAKEFILE=Yes -D eigen_prefix=prefix -D cppad_testvector=eigen ..`

**Comment by bradbell** [comment]
The case above works with my system and compiler.
What operating system are you using ?

**Comment by niclasbrok** [comment]
I used a mac with the following specs:

![image](https://user-images.githubusercontent.com/8836802/51387571-d2272a00-1b26-11e9-98af-2e47bbc8f20c.png)

**Comment by bradbell** [comment]
I do not have access to a MAC operation system (Apple does not provide for virtual MAC testing).
If you know how to use a debugger, would you please try the following:

1. Install Eigen in $HOME/prefix/eigen
2. Run
    bin/run_cmake.sh --verbose --eigen_vector
3. Run
   bin/test_one.sh example/abs_normal/abs_min_quad.cpp

This should create the file test_one.exe which runs that one test. 
You should then be able to run it in the debugger with
   gdb ./test_one.exe
   run
And you should be able to set break points in the file
  abs_min_quad.cpp
and see exactly which check is failing and  what the corresponding values are in the NearEqual check.

**Comment by niclasbrok** [comment]
It fails at 3. for the example min_nso_quad.cpp:

![image](https://user-images.githubusercontent.com/8836802/51478751-a311f200-1d8c-11e9-9491-49e9f271a1b7.png)

I managed to find a similar issue here: [link](https://github.com/JakobEngel/dso/issues/26) - it seems as if I have to change the CMakeLists.txt file?

**Comment by bradbell** [comment]
I think this problem can be fixed by adding the following statement
UNSET( $flag )
just before the line
CHECK_CXX_SOURCE_RUNS("${source}" ${flag} )
in the file
https://github.com/coin-or/CppAD/blob/master/example/multi_thread/CMakeLists.txt

Please test this on your system.

**Comment by niclasbrok** [comment]
No - the problem persists. I added the line here:

SET(flag ${idir}_${ldir}_${lname}_ok )
UNSET( $flag )
CHECK_CXX_SOURCE_RUNS("${source}" ${flag} )

**Comment by bradbell** [comment]
My mistake, I should have written
UNSET( ${flag} )
Please try that and see if it fixes the problem

**Comment by bradbell** [comment]
The problem was that minus signs can be in file names but not in variable names.
See the STRING( REGEX REPLACE in the commit
https://github.com/coin-or/CppAD/commit/2a4d59902caca5ad5653f5408f64513d5e0540f1

This was also fixed in version 20190200.1.

Please check if this works, and closes the bug for you ?

**Comment by niclasbrok** [comment]
Yes - now all tests pass. But it is still weird that it cannot find my boost multi-thread library when it is clearly installed:

-- Performing Test include_lib_boost_thread_mt_ok
-- Performing Test include_lib_boost_thread_mt_ok - Failed
-- Performing Test include_lib_boost_thread_ok
-- Performing Test include_lib_boost_thread_ok - Failed
-- Could not find boost multi-threading library

But when I run cmake test all tests pass.

**Comment by bradbell** [comment]
Perhaps you need to install something like libomp-devel on Fedora; see
https://bugzilla.redhat.com/show_bug.cgi?id=1677273

**Comment by niclasbrok** [comment]
I managed to make a minimum working example for the multi-thread example from cppad.

The program:

```
#include <boost/thread.hpp>
int main(void)
{   boost::barrier wait(1);
    return 0;
}
```

Can be compiled and executed using the CMakeLists.txt file:

```
find_package(Boost COMPONENTS thread)
if(Boost_FOUND)
    add_executable(boost_test main.cpp)
    target_link_libraries(boost_test ${Boost_LIBRARIES})
endif()
```
However, the example in example/multi_thread doesn't compile. The problem must be related to proper linking of the boost library in example/multi_thread/CMakeLists.txt?

**Comment by bradbell** [comment]
Looking at
https://stackoverflow.com/questions/26749461/how-to-determine-the-boost-library-names-for-cmake

It appears that the components part of only for object libraries, not include libraries.
In the file cppad.git/CMakeLists.txt please try changing the command
- FIND_PACKAGE(Boost)
to the command
- FIND_PACKAGE(Boost thread)
and see if this fixes the check in cppad.git/example/multi_thread/CMakeLists.txt

**Comment by bradbell** [comment]
The problem was that the boost threading object library depended on other boost object libraries.
This was accounted for in the commit
https://github.com/coin-or/CppAD/commit/15e793075f355dc5c5efbb3ceff29a6efc3d16da

Please test and see if the current version builds and runs
make check_example_multi_thread_bthread
on your system.

**Comment by niclasbrok** [comment]
Yes - now it works:

-- Performing Test boost_multi_thread_ok
-- Performing Test boost_multi_thread_ok - Success
-- make check_example_multi_thread_bthread: available
-- make check_example_multi_thread: available

**Comment by bradbell** [comment]
Thanks for your help with this issue.
