### ISSUE TITLE
assignment in assert

### ISSUE THREAD

**Issue by svigerske** [coin-or/CppAD#45]
Is this indeed meant to be an assignment, or you mean `==`?
https://github.com/coin-or/CppAD/blob/f0c5edcdf9687bf719b71bccf1b79d8f298b1d76/include/cppad/local/play/player.hpp#L258

**Comment by bradbell** [comment]
You are correct, there should be no side effects in the CppAD asserts.
In this case, the op is expected to be equal to BeginOp so doing the assignment does not break and code, but it does not check the expected condition. I will fix this.
Brad.

**Comment by bradbell** [comment]
I think this commit solves the problem:

If you agree, please close this issue.
