### ISSUE TITLE
Why forcing CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by jcarpent** [coin-or/CppAD#50]
Daer @bradbell,

I have a minor question concerning the default install prefix of CppAD. Currently, it is forced to the value of `cppad_prefix`, which is set to `/usr`. Is there any good fundamental reason to do as such?

https://github.com/coin-or/CppAD/blob/405ddc51e23e2b52beec774d0a1f4809f1f15197/CMakeLists.txt#L108

**Comment by bradbell** [comment]
This is a very good suggestion.

I wanted the cppad install prefix to be like the other prefixes that can be specified on the CMAKE comamnd line. 

I think you are correct, the default value should be the value for cppad_prefix should be CMAKE_INSTALL_PREFIX. I will try and get to this soon.

**Comment by jcarpent** [comment]
I can manage it if you don't have time. Let me know.

**Comment by bradbell** [comment]
I think I have made this change in the commit:
https://github.com/coin-or/CppAD/commit/879dbba6540d204bc57d27a70f6ceb85c0addebd

see the heading 10-02 on
https://bradbell.github.io/dismod_at/doc/whats_new_2019.htm#10-01

Please test this and if you are satisfied, please close this bug.

**Comment by jcarpent** [comment]
Sounds perfect for me. Thanks a lot for the quick reply.
