### ISSUE TITLE
20200000.0 installs an empty directory include/cppad/utility/omh

### ISSUE THREAD

**Issue by yurivict** [coin-or/CppAD#52]

**Comment by bradbell** [comment]
I think that the following commit fixed this:
    https://github.com/coin-or/CppAD/commit/78e28ee13cf53f26edc53597536fa5fbf6d34063
This is included in the following release:
    https://github.com/coin-or/CppAD/releases/tag/20200000.1

**Comment by bradbell** [comment]
Please close this bug if the the new release 20200000.1 fixes the problem for you (yurivict).

**Comment by yurivict** [comment]
Yes, it fixed the problem.

Thanks!
