### ISSUE TITLE
Best way to get the version of CppAD with CMake

### ISSUE THREAD

**Issue by joaoleal** [coin-or/CppAD#53]
Hello Brad,

What would be the best way to determine the version of CppAD with CMake after it has been installed to a custom folder?
PkgConfig is easy to use to extract the version if CppAD is installed in the system but not in a custom folder.
If there was a generated file with the version next to the sources would be great.

**Comment by bradbell** [comment]
I use the variable cppad_version in the top level CMakeLists.txt file.
To be specific, I use
grep '^SET( *cppad_version *"[0-9]*" *)' CMakeLists.txt | sed -e 's|.*"\([0-9]*\)".*|\1|'

This is not yet in the API, but perhaps it should be.

The symbol CPPAD_PACKAGE_STRING 
https://coin-or.github.io/CppAD/doc/preprocessor.htm#Documented%20Here.CPPAD_PACKAGE_STRING
contains the version number. Perhaps this needs more documentation as to its format.

**Comment by joaoleal** [comment]
Excellent.
The symbol CPPAD_PACKAGE_STRING is exactly what I need. It is easy to see the format in configure.hpp.in.
Thank you.

**Comment by bradbell** [comment]
@joaoleal If you are satisfied with this solution, would you please close this issue.
