### ISSUE TITLE
Jacobian elements order

### ISSUE THREAD

**Issue by mohamdev** [coin-or/CppAD#54]
Hello,

First I want to take you for your awesome work which is very helpful to me. I just have a question. When I get the Jacobian of my recoded function, I get a big vector instead of a matrix. For example, My Jacobian should me a 3*13 matrix, but instead, I get a 39*1 vector. This is ok because I guess all the ellements of my matrix are inside this vector, but how can I know in which order they are ? 

Thank you very much for you feedback, and do not hesitate to ask me if I weren't clear enough.

**Comment by bradbell** [comment]
Which routine are you calling to get the Jacobian, sparse (Jacobians have a special storage) ?

**Comment by mohamdev** [comment]
I used some dynamic lib code generation with CppADCodeGen, so I call it this way : 

```c++

    LinuxDynamicLib<Scalar> fkine_Linear_Lib(FKINE_LINEAR_EXT);
    std::unique_ptr<GenericModel<double>> fkine_linear_model = fkine_Linear_Lib.model("fkine_linear");
    jac_positions = fkine_linear_model->Jacobian(q);

```

**Comment by joaoleal** [comment]
Hello,

The method `model->Jacobian(q);` returns the entire dense Jacobian (m x n) in a vector.
It provides the elements in the same order as calling CppAD `JacobianFor` or `JacobianRev`:
```Latex
jac[ i * n + j ] = \D{ F_i }{ x_j } ( x )
i = 0 , ... , m - 1
j = 0 , ... , n - 1
```
The documentation is missing for those methods. I'll add this information.

**Comment by mohamdev** [comment]
Great ! thank you very much for your help :)
