### ISSUE TITLE
Generated pkgconfig file not compliant with the standard 

### ISSUE THREAD

**Issue by GiulioRomualdi** [coin-or/CppAD#62]
The `cppad.pc` file generated by the library does not contain the usual structure
```
prefix=${pcfiledir}/../..
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
```
However, this creates several problems when I tried to import the library in `vcpkg` https://github.com/microsoft/vcpkg/pull/12560

Indeed as @Neumann-A suggested in https://github.com/microsoft/vcpkg/pull/12560#issuecomment-666373589 the `prefix` variable must be defined in every pkg-config file.

FYI @traversaro

**Comment by GiulioRomualdi** [comment]
https://github.com/coin-or/CppAD/pull/63 should fix the issue

**Comment by bradbell** [comment]
I have added the requested extra variables to the cppad.pc and cppad-uninstalled.pc files. See the heading Extra Definitions on
https://coin-or.github.io/CppAD/doc/pkgconfig.htm#cppad.pc.Extra%20Definitions

For more information about the change, see the heading 12-02 on
https://coin-or.github.io/CppAD/doc/whats_new_20.htm#12-02

Or for even more, see the commit
https://github.com/coin-or/CppAD/commit/cabee29677b6df1dd23cbec52b3d609ca08cdd40

> The `cppad.pc` file generated by the library does not contain the usual structure
> 
> ```
> prefix=${pcfiledir}/../..
> exec_prefix=${prefix}
> includedir=${prefix}/include
> libdir=${exec_prefix}/lib
> ```
> 

Does this addition to cppad.pc resolve this issue ?

**Comment by bradbell** [comment]
@GiulioRomualdi Does this solve the issue for you ? If so, would you please close it.

**Comment by traversaro** [comment]
Thanks @bradbell, I think that solved the issue. The definitive test wil be done when we update the cppad version used in vcpkg, and we try to remove the patches added in https://github.com/microsoft/vcpkg/pull/12560.
