### ISSUE TITLE
Outputting nan though the values are right

### ISSUE THREAD

**Issue by vimalrajayyappan** [coin-or/CppAD#67]
AD<double> AngleDiff( AD<double> valueA, AD<double> valueB)
{
  return CppAD::acos( (CppAD::cos(valueA)*CppAD::cos(valueB)) + (CppAD::sin(valueA)*CppAD::sin(valueB)) );
}

AD<double> output = CppAD::pow( AngleDiff(AD<double> Variable1, AD<double> Variable2 ),2)

I'm getting nan value in the output. I just checked the inputs they all are right. Kindly help me with this. Will be greatly appreciated. The error I got is..

cppad-20160000.1 error from a known source:
yq = f.Forward(q, xq): has a non-zero order Taylor coefficient
with the value nan (but zero order coefficients are not nan).
Error detected by false result for
    ok
at line 244 in the file 
    /usr/include/cppad/local/forward.hpp
mpc: /usr/include/cppad/utility/error_handler.hpp:207: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion `false' failed.
Aborted (core dumped)

**Comment by bradbell** [comment]
Perhaps you need to use
https://coin-or.github.io/CppAD/doc/pow_int.htm
