### ISSUE TITLE
vector: index greater than or equal vector size

### ISSUE THREAD

**Issue by Tengyun-Mo** [coin-or/CppAD#68]
when I use cppad I get this error:

_cppad-20200905 error from a known source:
vector: index greater than or equal vector size
Error detected by false result for
    i < length_
at line 341 in the file 
    /usr/local/include/cppad/utility/vector.hpp
MPC_Node: /usr/local/include/cppad/utility/error_handler.hpp:206: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion false failed
Aborted (core dumped)_

Does anyone know how to fix it? I'm very appreciate it!

**Comment by bradbell** [comment]
Would you please close this issue if this solves it for you.

**Comment by hichamhendy** [comment]
I happen to run against this problem in actually a very trivial line namely
`std::cout << solution.x[x_start + 1];` and `CppAD::ipopt::solve_result<Dvector> solution;`  abd by the way `const size_t x_start = 0;

any ideas?`

**Comment by passer-by-Wang** [comment]
hello， I met this issue ,too. Could you please give a solution of if you have solved it?

**Comment by bradbell** [comment]
@passer-by-Wang Have you tried running the program in a debugger like gdb ?

**Comment by passer-by-Wang** [comment]
could you please give me more details about a debugger like gdb? I run it in terminal in ubuntu. Commands are as follow:
mkdir build
cd build
cmake ../
make
./cppad_ipopt_demo

**Comment by passer-by-Wang** [comment]
actually, it successes under ubuntu system of VMware but fails under ubuntu system under my Desktop computer with dual systems

**Comment by bradbell** [comment]
Here is a gdb tutorial:
https://web.eecs.umich.edu/~sugih/pointers/summary.html

**Comment by bradbell** [comment]
@passer-by-Wang Did the suggestion above work for you ?
