### ISSUE TITLE
Use several ADFun<Base> in another ADFun using Eigen vectors

### ISSUE THREAD

**Issue by mohamdev** [coin-or/CppAD#71]
Hi,

First I want to thank you for you amazing work which is really helpful for my projects.
I have a small problem, I want to know if it's possible to record an ADFun<Base> with other ADFun inside it. Let me show a simplified example of my problematic : 

```c++
typedef AD<double> AD_double;
typedef Eigen::Matrix<AD_double,Eigen::Dynamic,Eigen::Dynamic> ADMatrix;
typedef Eigen::Matrix<AD_double,Eigen::Dynamic,1> ADVector;

int main{

ADVector InputVector;
ADVector Parameters;

//Record a first tape
Independent(InputVector, Parameters);

/*Sequence 1
*
*
*/
ADVector Output_1 = sequence_1_result;

ADFun<double> function_1(InputVector, Output_1);


//Record a second tape
Independent(InputVector, Parameters);

/*Sequence 2
*
*
*/
ADVector Output_2 = sequence_2_result;

ADFun<double> function_2(InputVector, Output_2);

//Record a thrid tape containing function_1 and function_2
Independent(InputVector, Parameters);

function_1.new_dynamic(Parameters);
function_2.new_dynamic(Parameters);
ADVector OutputFinal = function_1.Forward(0, InputVector) + function_2.Forward(0,InputVector);

ADFun<double> final_func(InputVector, OutputFinal);

}
```
When doing this in my code, for the lines `function_1.new_dynamic(Parameters); function_1.new_dynamic(Parameters);` and `ADVector OutputFinal = function_1.Forward(0, InputVector) + function_2.Forward(0,InputVector);` I get the following error : 

`/usr/local/include/cppad/core/forward/forward.hpp:177:45: error: cannot convert ‘const CppAD::AD<double>’ to ‘double’ in assignment`

I dont know how to solve it. Of course I could put all the sequences in a single ADFun, but it would be very useful in my project to use several ADFun layered.

Thank you in advance for your help :-)

**Comment by bradbell** [comment]
The easiest way to do this is to create an ADFun< AD<double> > version of function_1 and function_2; e.g.
ad_function_1 = function_1.base2ad()
ad_function_2 = function_2.base2ad()

Then ad_function_1 and ad_function will operate on AD<double> object during their derivative caluclations.

**Comment by mohamdev** [comment]
When I tried to create `ADFun< AD <double > >`, the command `ad_function_1 = function_1.base2ad()` did not work.
If I do `ADFun<AD<double>, double>` it works fine and the code compiles. Thank you very much for your help :-)

Best regards
