### ISSUE TITLE
Compilation issue with Eigen vectors and CppAD scalar

### ISSUE THREAD

**Issue by mfrigerio17** [coin-or/CppAD#72]
Hi,
The following simple code fails to build for me:

```c++
#include <Eigen/Dense>
#include <cppad/cppad.hpp>
#include <cppad/example/cppad_eigen.hpp>

int main()
{
    using Scalar = CppAD::AD<double>;
    //using Scalar = double;

    Eigen::Matrix<Scalar, 1,4> row;
    Eigen::Matrix<Scalar, 4,1> col;
    Eigen::Matrix<Scalar, 4,1> vec;
    
    Scalar res2 = row * col + vec(2); //fails

    return 0;
}
```
The g++ compiler error is:
```
cppad-eigen-problem.cpp: In function ‘int main()’:
cppad-eigen-problem.cpp:18:29: error: no match for ‘operator+’ (operand types are ‘const Eigen::Product<Eigen::Matrix<CppAD::AD<double>, 1, 4>, Eigen::Matrix<CppAD::AD<double>, 4, 1, 0, 4, 1>, 0>’ and ‘Eigen::DenseCoeffsBase<Eigen::Matrix<CppAD::AD<double>, 4, 1, 0, 4, 1>, 1>::Scalar’ {aka ‘CppAD::AD<double>’})
   18 |     Scalar res2 = row * col + vec(2); //fails
      |                   ~~~~~~~~~ ^ ~~~~~~
      |                       |          |
      |                       |          Eigen::DenseCoeffsBase<Eigen::Matrix<CppAD::AD<double>, 4, 1, 0, 4, 1>, 1>::Scalar {aka CppAD::AD<double>}
      |                       const Eigen::Product<Eigen::Matrix<CppAD::AD<double>, 1, 4>, Eigen::Matrix<CppAD::AD<double>, 4, 1, 0, 4, 1>, 0>
```
So, basically, with the CppAD double, Eigen fails to realize that the vector product yields a scalar, so that another scalar can be added to it.
Setting `Scalar` to `double` does not reproduce the issue, so I suspect it is a problem in the CppAD Eigen-traits ?

I have Eigen 3.3.7 and the latest master of CppAD, g++ 9.3.0.

The problem can be circumvented by adding `value()`, as in

```
Scalar res2 = (row * col).value() + vec(2);
```
but for me that is not an option, because it requires changing code that already works when the selected scalar is not the CppAD double.

Thanks

**Comment by bradbell** [comment]
I am a little confused by the example:

1. row is a 1x4 matrix, col is a 4x1 matrix and row*col is a 1x1 matrix ?

2. vec is a 4x1 matrix but what is vec(2) ?

Would you please give values to the input matrices and report the result (for the double case); e.g.,
row << 1,1,1,1;
col << 2,2,2,2;
vec << 3,3,3,3;

res2 = 11 ?

**Comment by mfrigerio17** [comment]
>    row is a 1x4 matrix, col is a 4x1 matrix and row*col is a 1x1 matrix ?

yes. Which is the "same" as a scalar. A row vector times a column vector is a scalar.

>    vec is a 4x1 matrix but what is vec(2) ?

A scalar. The `()` is just the indexing operator, so I am taking the third coordinate of a vector. It is just a way of getting a scalar.
Oh, I realized, I should have used directly a scalar, to have a simpler example. Like this:

```c++
    Eigen::Matrix<Scalar, 1,4> row;
    Eigen::Matrix<Scalar, 4,1> col;
    Scalar scalar = 5;
    
    Scalar res2 = row * col + scalar; //still fails, for the same reason
```
Sorry about it.

> res2 = 11 ?

Yes. With the values you picked, that is correct.

Does this clarify the example?
Thanks

**Comment by bradbell** [comment]
My mistake. I forgot that eigen uses parenthesis for element access. 

Perhaps you could tell me what needs to be different in 
https://coin-or.github.io/CppAD/doc/cppad_eigen.hpp.htm
or the corresponding source code
https://github.com/coin-or/CppAD/blob/master/include/cppad/example/cppad_eigen.hpp

Also, perhaps you could point me to the eigen documentation that discusses the issue.

**Comment by mfrigerio17** [comment]
> Perhaps you could tell me what needs to be different in

I have no idea. Actually, your Eigen traits look complete to me.

There is a [question](https://stackoverflow.com/q/65019299/9908011) on StackOverflow about this problem, so maybe we can get some information from the answers there.

**Comment by jcarpent** [comment]
I think the issue is not related to Eigen but rather to the overloading of operator+ by CppAD::AD<Scalar> types.

**Comment by bradbell** [comment]
Is there some place in the eigen documentation that describes what is missing from the Cppad::AD types ?

**Comment by jcarpent** [comment]
I think the only thing to do is for any Eigen::MatrixBase, to cast it as scalar before performing the addition.

**Comment by mfrigerio17** [comment]
mhmmm... Eigen somehow realizes that the product is a scalar, when using other scalar types, with no need for a cast. So why does it not do it when using the CppAD scalar?

For example, this is another scalar type:

```c++
struct MyDouble {
    MyDouble() : val(0) {}
    explicit MyDouble(double v) : val(v) {}

    double val;
};

MyDouble operator*(const MyDouble& lhs, const MyDouble& rhs) {
    return MyDouble(lhs.val*rhs.val);
}

MyDouble operator+(const MyDouble& lhs, const MyDouble& rhs) {
    return MyDouble(lhs.val+rhs.val);
}

namespace Eigen {
template<> struct NumTraits<MyDouble> : NumTraits<double>{};
}
```

which does *not* reproduce the problem. That is, it works fine.

**Comment by mfrigerio17** [comment]
> Is there some place in the eigen documentation that describes what is missing from the Cppad::AD types ?

There is some documentation about custom scalar types [here](https://eigen.tuxfamily.org/dox/TopicCustomizing_CustomScalar.html), but it looks that CppAD is already conforming to the rules

**Comment by bradbell** [comment]
> namespace Eigen {
> template<> struct NumTraits<MyDouble> : NumTraits<double>{};
> }

Try just supplying the traits that are in the Eigen API. This may be a new feature request for eigen; i.e., that they publish and support more traits.

**Comment by tellenbach** [comment]
*Eigen maintainer here, found this issue via [StackOverflow](https://stackoverflow.com/questions/65019299/row-times-column-is-not-a-scalar-with-custom-scalar-type-cppad)*

> yes. Which is the "same" as a scalar. A row vector times a column vector is a scalar.

While mathematically true, C++  is a different story: The return type of `operator*` in `row * col` is not a scalar and neither a (1x1) matrix but a product expression. This product expression is implicitly convertible to the scalar type of its operands, in this case `CppAD::AD<double>`.

The reason for the error you see is that `CppAD::AD<double>` is a template and its operators are thus function templates, e.g. something like

```
template<typename T>
CppAD::AD<T> operator+(const CppAD::AD<T>& lhs, const CppAD::AD<T>& rhs);
```

The problem now is that the above *templated* `operator+` cannot be called since there is no implicit conversion in template arguments and exactly this would be needed to cast the product expression to `CppAD::AD<double>`.

> For example, this is another scalar type:
> [...]
> which does not reproduce the problem. That is, it works fine.

As explained above this is a fundamentaly different case. Make `MyDouble` a template and you'll see the same failue.

That's also the reason why avoiding the product works (e.g. by using Eigen's `.dot` function).

Nevertheless you can solve this problem by e.g. defining an appropriate `operator+`, something like (not tested)

```
template<typename Derived>
Scalar operator+(const MatrixBase<Derived>& lhs, const MatrixBase<Derived>& rhs) {
  return lhs.derived().coeff(0, 0) + rhs;
                     //^^^^^^^^^^^ No need for an implicit conversion
}
```

**Comment by bradbell** [comment]
To be clear, if in the original example we change
    using Scalar = CppAD::AD<double>;
to
    using Scalar = std::complex<double>;

The example does not compile (I have verified this).  So, if one were to fix this in Eigen, the complex case would be a more motivating example.

**Comment by mfrigerio17** [comment]
> So, if one were to fix this in Eigen, the complex case would be a more motivating example.

I agree.

Anyway, the workaround proposed by @tellenbach works, so I would close the issue.

Once again, for the records, the link to the [Stackoverflow question](https://stackoverflow.com/q/65019299) corresponding to this issue.
