### ISSUE TITLE
How to add matrix constraints?

### ISSUE THREAD

**Issue by EdisonKun** [coin-or/CppAD#73]
Dear developers, thanks  for the contribution on this awesome project. I want to know how to add the matrix constrains in the FG_eval function, like:
```
   min     f(x)
  x ∈ Rⁿ

s.t.       g_L ≤ g(x) ≤ g_U
           x_L ≤  x   ≤ x_U
``` where g(x) is a matrix and g_L,g_U is the vector?
Can you give me some advice? Thank you.

**Comment by bradbell** [comment]
If  x and y are vectors of length n, x <= y means x_i <= y_i for i = 0, ..., n-1.
What do you mean by a vector is be less than or equal a matrix ?

**Comment by EdisonKun** [comment]
Thanks for your quickly reply~Yes, what I mean is x<=y means x_i <=y_i for i = 0,...,n-1; This is used for the IPOPT calculation to add constraints;
for example:
```
g(x)=A(x)*x;
void operator()(ADvector& fg, const ADvector& x)
{
      vector result;
      result = A(x)*x;
      fg[1]=result(1);
      fg[2]=result(2);
};
```
where A(x)=[x1 * x2 * x3 , x1; x2 * x1 , 1]; and x=[x1; x2];
I know this can convert to the formula expression like:
```
fg[1]=x1*x1*x2*x3+x1*x2;
fg[2]=x2*x1*x1+x2;
```
But if I make some complex computations, like the robot forward kinematics calculation. I can not express it to the formula expression easily. What I can get is the A(x) and x. So do you any suggestions? thank you~

**Comment by bradbell** [comment]
One could use eigen to do the multiplication
```
Ax =  A(x) * x
```
and then set
```
fg[1] = Ax[0]
fg[2] = Ax[1]
...
For examples using eigen with CppAD see;
https://coin-or.github.io/CppAD/doc/eigen_prefix.htm

**Comment by EdisonKun** [comment]
It works!!!!!thank for your kindness help~
Dear bradbell,  you are my today's hero!!

**Comment by bradbell** [comment]
Please close this issue (I like to have the person that opens an issue close it so I am sure they are satisfied).

**Comment by EdisonKun** [comment]
OK, thank you so much~~~
