### ISSUE TITLE
using ::isnan instead of s != s in CppAD/include/cppad/utility/nan.hpp

### ISSUE THREAD

**Issue by erwincoumans** [coin-or/CppAD#74]
In Visual Studio 2019, using Fast (/fp:fast),  the check s!=s doesn't work as intended, but ::isnan works fine.

Would it be possible to use ::isnan, since it is part of the C++11 standard?

~~~~~~~~~~~~~~~~~~
template <class Base>
inline bool isnan(const cg::CG<Base> &s) {
    using namespace CppAD::cg;

    if (s.isVariable()) {
        return false;
    } else {
        // a parameter
        const Base& v = s.getValue();
        return ::std::isnan(v);
    }
}
~~~~~~~~~~~~~~~~~~

**Comment by bradbell** [comment]
Yes. I Recently converted CppAD to require c++11, so this is an easy change.
This is a good example to check CppAD pull request testing  on github with.
There  have both travis and appveyor tests; see 
https://github.com/coin-or/CppAD/blob/master/.travis.yml
https://github.com/coin-or/CppAD/blob/master/appveyor.yml

If you make a pull request, will it automatically run those ?

**Comment by bradbell** [comment]
Ooops. Is this a change request for CppAD or CppADCodeGen ?

**Comment by erwincoumans** [comment]
CppAD, sure, I'll create a PR in a sec.

**Comment by bradbell** [comment]
Can you reproduce this problem with just CppAD; i.e., perahps it should be changed here :
https://github.com/coin-or/CppAD/blob/master/include/cppad/utility/nan.hpp
where the following text appears:
template <class Scalar>
bool isnan(const Scalar &s)
{   return (s != s);
}

**Comment by erwincoumans** [comment]
That the kind of test I added for CppADCodeGen, I'll add a PR for CppAD as well

Here is a PR, feel free to ignore/close it as well:
https://github.com/coin-or/CppAD/pull/75

~~~~~~~~~~~~~~
template <class Scalar>
bool isnan(const Scalar &s)	bool isnan(const Scalar &s)
{   return (s != s);	{
  if constexpr (std::is_floating_point<Scalar>::value) 
  {
      return ::std::isnan(s);
  }
  else {
      return (s != s);
  }
}	}
~~~~~~~~~~~~~~

**Comment by erwincoumans** [comment]
Ah, you don't enable C++17, so constexpr won't work, closing, since the issue I face is in CppADCodegen.

**Comment by bradbell** [comment]
Now that C++11 is assumed, I am going to start adding use of C++17 features, but also provide backward compatibility with C++11. Probably until 2027 (when C++17 is 10 years old). Then moving forward to the next standard in a similar fashion.
