### ISSUE TITLE
yq = f.Forward(q, xq): a zero order Taylor coefficient is nan

### ISSUE THREAD

**Issue by Chuan701** [coin-or/CppAD#87]
cppad-20160000.1 error from a known source:
yq = f.Forward(q, xq): a zero order Taylor coefficient is nan.
Corresponding independent variables vector was written to binary a file.
vector_size = 133
file_name = /tmp/fileDJXt7B
index = 62

Error detected by false result for
if( CppAD::isnan( yq[ (q+1) * index + 0 ] )
at line 224 in the file
/usr/include/cppad/local/forward.hpp
mpc: /usr/include/cppad/utility/error_handler.hpp:207: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion `false' failed.
Aborted (core dumped)

Does everyone encountered the same problem with MPC? 
Thank you!

**Comment by bradbell** [comment]
Would you please open a new discussion for this under General at 
https://github.com/coin-or/CppAD/discussions/categories/general
