### ISSUE TITLE
eps = 0 on Visual Studio 2010

### ISSUE THREAD

**Issue by Loutjie** [coin-or/CppAD#9]
eps =0.0 on Visual Studio 2010. The issue was resolved by changing std::numeric_limits&lt; zdouble&gt;::epsilon() to std::numeric_limits&lt; double&gt;::epsilon() in zdouble.hpp

Similar for std::numeric_limits::min() and std::numeric_limits::max()

**Comment by bradbell** [comment]
I believe I fixed this with the commit
     https://github.com/coin-or/CppAD/commit/cc45bd84261692cfeac9ec2148f75200af785bb2

Unfortunately, I have a new version of the auto-tools on my system and it automatically changed the related files (for the deprecated auto-tools install process). So the autotool changes are mixed in with the commit.
