### ISSUE TITLE
Potential for optimize to break an atomic

### ISSUE THREAD

**Issue by perrydv** [coin-or/CppAD#99]
Hi @bradbell 

[Here is a toy example](https://github.com/perrydv/CppADtests/tree/main/optimize_breaks_atomic) where a tape with an atomic_three works if not optimized and breaks in first-order reverse if optimized.  Is it a bug or am I making a mistake?

 In this minimal toy example it breaks by aborting due to an assertion.  In the full case I'm tracking down, it fails silently with wrong results (nans).

I think the issue is that optimizing deduces when elements of 0th-order taylor_y (value) should not mathematically be needed, and then it doesn't put them in taylor_y when calling the atomic's reverse function.  Does that sound right?  In this example, the atomic has n = 2, m = 2.  y[0] depends on x[0] and x[1].  y[1] depends on only x[1].  If subsequent computations only use y[1], then in reverse mode, partial_y[0] is 0 and taylor_y[0] is not provided (it is nan).  It seems that to use this input correctly one has to be careful not to propagate that nan. Is this intended / documented behavior? If optimize has not been used, then the taylor_y[0] value *is* provided in input to reverse. 

(Of course in this case, since y[0] is not used in subsequent computations, one could specialize the code to avoid the problem, but the goal is to not have an atomic break based on how its results are used.)

Thanks for any help.

**Comment by bradbell** [comment]
I turned on tracing during zero order forward mode with the folloing command
`bin/trach.sh forward0.hpp 1`
The following trace was generated before optimization:
```
o=1    v=1    Inv     | fz[0]=3.4
o=2    v=2    Inv     | fz[0]=4.5
o=3    v=     AFun     f=atom* i=0     n=2     m=2    
o=4    v=     Funav     v=1    
o=5    v=     Funav     v=2    
o=6    v=3    Funrv   | fz[0]=119.981
o=7    v=4    Funrv   | fz[0]=90.0171
o=8    v=     AFun     f=atom* i=0     n=2     m=2    
o=9    v=5    Mulvv    vl=4     vr=4    | fz[0]=8103.08
o=10   v=     End     
```
The following trace was generated after optimization:
```
o=1    v=1    Inv     | fz[0]=3.4
o=2    v=2    Inv     | fz[0]=4.5
o=3    v=     AFun     f=atom* i=0     n=2     m=2    
o=4    v=     Funav     v=1    
o=5    v=     Funav     v=2    
o=6    v=     Funrp     p=nan  
o=7    v=3    Funrv   | fz[0]=90.0171
o=8    v=     AFun     f=atom* i=0     n=2     m=2    
o=9    v=4    Mulvv    vl=3     vr=3    | fz[0]=8103.08
o=10   v=     End    
```
It is clear that the optimizer thinks the function result is a parameter (`Funrp`) instead of a variable (`Funrv`)
I will look into why this is the case

**Comment by bradbell** [comment]
During the reverse mode call
```
bool atomic_three<Base>::reverse(
    const vector<Base>&         parameter_x ,
    const vector<ad_type_enum>& type_x      ,
    size_t                      order_up    ,
    const vector<Base>&         taylor_x    ,
    const vector<Base>&         taylor_y    ,
    vector<Base>&               partial_x   ,
    const vector<Base>&         partial_y   )
    ```
If a partial_y is zero, this can mean that the fucntion value does not depend on that value of y and even if the corresponding derivative of y w.r.t x is infinite or nan, the partial with respect to x should be zero. i need to write more about this in the documentation. Suffices it to say that in your case, the derivatives can be fixed using absolute zero multipliers as follows:
```
      // adjoint of x[0] = (adjoint of y[0]) * exp(x[0])
    partial_x[0 + 0*nrow] = CppAD::azmul(
        partial_y[0 + 0*nrow] , exp_x0
    );
      // adjoint of x[1] = (adjoint of y[0] + adjoing of y[1]) * exp(x[1])
    partial_x[0 + 1*nrow] = CppAD::azmul(
        partial_y[0 + 0*nrow] + partial_y[0 + 1*nrow], exp_x1
    );
```

**Comment by bradbell** [comment]
Please indicate if this solves your problem ?

**Comment by perrydv** [comment]
Thanks for the explanation and tracing demo.  That's consistent with what I thought was going on.

I see the workaround for this particular toy example, but is there a way to not have optimization block the taylor_y elements even if they should not be needed?  I realize that would mean it would be less optimized, but it might allow faster code within the atomic and would support writing atomics that are more general purpose.

Here is something closer to the full example of interest.  I have an atomic for matrix operations.  Input and output are matrices.  I want the atomic to work regardless of how the output matrix is used in later computations in the tape.  In one case it was used only for its diagonal elements.  That meant non-diagonal elements became nans in 0th order taylor_y when reverse was called, for the same reason the first element in the toy example was nan.  The reverse-mode calculations use an external library (Eigen, called using Eigen::Map<>s pointing at taylor_y and other inputs), and the nans end up propagating around the results in a bad way.  

If having nans in elements of taylor_y is the intended behavior, then does my reverse need to be programmed to potentially check every element of partial_y (and related objects) to decide what to do with them in case they are nans?  That would add cost and I think require memory allocation and copying to put together a full 0th order object (without nans, to pass to other functions) in my use case.

These atomics are meant to be tools used in arbitrary code, so it is not just about solving one particular problem.  From the point of view of an atomic as self-contained code that should work correctly even in wasteful cases (like when all of its return values aren't actually needed), it seems complicated that the atomic might not work depending on what is done with its outputs later, or that checking each input may be needed.  Does that make sense?

**Comment by bradbell** [comment]
This is a more general problem (not just the optimization setting) where nans and infinities can come up when computing derivatives. I have added some explantion under the heading azmul on 
https://coin-or.github.io/CppAD/doc/atomic_three_reverse.htm#partial_x.azmul

In addition, I have changed the atomic three reverse example to do this; see
https://coin-or.github.io/CppAD/doc/atomic_three_reverse.cpp.htm

There is wish list item about adding separate information to the tape specifying which variables are selected; see the heading Reverse Mode on
https://coin-or.github.io/CppAD/doc/wish_list.htm#Reverse%20Mode

**Comment by bradbell** [comment]
The value nan is being used in
`o=6    v=     Funrp     p=nan`
to make sure that the results do not depend on that value.
This is in-case the person implementing the atomic fucntion makes a mistake in the calculation of the depend_x.
I could change the value fot zero, but then people might not know if they had made this mistake.
I could add an option to the optimizer that switches between zero and nan.
This would be better because it would give people a way to find out if they had made this mistake.

**Comment by perrydv** [comment]
Thanks for all the info.  I'm seeing more of the generality of the problem.

BTW, I think the `atomic_three_reverse` documentation has a misplaced extra "Upon return" statement for taylor_y.

Is it feasible to have an option to the optimizer that tells it to put the actual taylor_y values (maybe from the parameters), or are those not easily available at that point?

Would it be dangerous to let taylor_y be non-const so the atomic can work in place on it?  I'm not sure that's a good idea.

**Comment by bradbell** [comment]
I now consider this a true bug and I think I have fixed it with the following commit:
https://github.com/coin-or/CppAD/commit/9253a9598a8f6b3f10e9978754033ec385ad9cdc
This includes backing out the change to the atomic_three example and an automated test for the bug.
The real fix is in the optimzie_run.hpp file.

Please try the new version and see if it works for you.

P.S.
You are correct about the extra 'Upon return' and I will fix it.

**Comment by bradbell** [comment]
I am not sure if I should make a new 2020 release with this change. The reason is that I added documentation to describe the change; i.e., the fact that optimized out values get set to zero; see the heading azmul on
https://coin-or.github.io/CppAD/doc/atomic_three_reverse.htm#partial_x.azmul
The rule is that CppAD does not add new features when it make bug fixes to a version.

**Comment by perrydv** [comment]
I will try the new version later.

**Comment by bradbell** [comment]
I have created a new release with this fix. The changes on stable/20210000 can be seen at
https://github.com/coin-or/CppAD/commit/0eb16a104e61a8c178b9dbd214de0818ba53ccb5

The new release is
https://github.com/coin-or/CppAD/releases/tag/20210000.5

**Comment by perrydv** [comment]
Sorry for the delay here.  The changes do fix the minimal example and also the more involved case I had.  If I follow, you changed the nans to 0s.  I wonder if there could be cases where an unexpected 0 creates a bug in user code if they are not aware it might happen.  But yes I can confirm my original problem is resolved.  Thanks for taking care of it so quickly.

**Comment by bradbell** [comment]
The value should not matter except it must be such that, when multiplied by zero, it results in zero.  Nan and infinity are the only values that do not satisfy this criteria.

Please close this issue (I like for the person who opens an issue to close it).

**Comment by perrydv** [comment]
👍
